#!/usr/bin/env bash
#
# api-reference.sh — writes api-docs/reference.md from the `api_v1` function catalog and the
# COMMENT on each function in the local database (the comments are the doc source:
# Purpose / Inputs / Returns / Errors).
#
#   scripts/api-reference.sh            regenerate api-docs/reference.md
#   scripts/api-reference.sh --check    fail (exit 1) if the committed file differs from a fresh render
#   scripts/api-reference.sh --out F    write to F instead
#
# Reads the running local stack (docker exec into the project's database container, so no psql is
# needed on the host). Environment:
#   MOS_DB_CONTAINER       database container name (default: supabase_db_<project_id> from config.toml)
#   MOS_API_CATALOG_JSON   render from this catalog file and skip the database (self-test)
#
# A function whose comment does not follow "Purpose: … Inputs: … [Returns: …] Errors: …" (or
# "Always raises: …" in place of Errors) fails the run: an undocumented operation cannot ship.
set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$REPO/api-docs/reference.md"
CHECK=0
while [ "$#" -gt 0 ]; do
  case "$1" in
    --check) CHECK=1 ;;
    --out) OUT="${2:?--out needs a path}"; shift ;;
    *) echo "usage: $0 [--check] [--out FILE]" >&2; exit 2 ;;
  esac
  shift
done

command -v jq >/dev/null || { echo "api-reference: jq is required" >&2; exit 2; }

CATALOG_SQL="$(cat "$REPO/scripts/lib/api-catalog.sql")"

if [ -n "${MOS_API_CATALOG_JSON:-}" ]; then
  CATALOG="$(cat "$MOS_API_CATALOG_JSON")"
else
  PROJECT_ID="$(sed -n 's/^project_id *= *"\(.*\)"/\1/p' "$REPO/supabase/config.toml" | head -1)"
  CONTAINER="${MOS_DB_CONTAINER:-supabase_db_${PROJECT_ID}}"
  CATALOG="$(printf '%s\n' "$CATALOG_SQL" | docker exec -i "$CONTAINER" psql -U postgres -d postgres -At -v ON_ERROR_STOP=1 -f -)" \
    || { echo "api-reference: could not read the catalog from container $CONTAINER (is the local stack up?)" >&2; exit 2; }
fi

[ "$(printf '%s' "$CATALOG" | jq 'length')" -gt 0 ] \
  || { echo "api-reference: the catalog holds no api_v1 functions; refusing to write an empty reference" >&2; exit 2; }

# jq: parse each comment, group by area, render Markdown.
RENDER='
def area:
  if . == "whoami" or . == "list_people" or . == "list_teams" or . == "list_business_units" then "Session and directory"
  elif . == "refused_action" then "Refusals"
  elif test("signal") then "Signals"
  elif test("project.*process") then "Projects and Processes"
  elif test("objective|key_result") then "Objectives"
  elif test("task|checklist_item") then "Tasks"
  else "Other operations" end;
def areas: ["Session and directory","Tasks","Signals","Projects and Processes","Objectives","Refusals","Other operations"];
def placeholder:
  if .type == "uuid" then "\"<uuid>\""
  elif .type == "uuid[]" then "[\"<uuid>\"]"
  elif .type == "text[]" then "[\"<text>\"]"
  elif .type == "text" then "\"<text>\""
  elif .type == "date" then "\"YYYY-MM-DD\""
  elif .type == "timestamp with time zone" then "\"<timestamp>\""
  elif .name == "write_up" then "[]"
  elif .type == "jsonb" then "{}"
  elif .type == "boolean" then "true"
  elif .type == "integer" or .type == "numeric" then "0"
  else "null" end;
def parse:
  (.comment // "") as $c
  | ($c | capture("^Purpose: (?<purpose>.*?) Inputs: (?<inputs>.*?)(?: Returns: (?<returns>.*?))?(?: Errors: (?<errors>.*?)| Always raises: (?<raises>.*?))$"))
  // error("api_v1." + .name + ": comment does not follow Purpose / Inputs / [Returns] / Errors");
def section($f):
  . as $fn
  | ($fn | parse) as $p
  | "### `\($fn.name)`\n\n"
    + "\($p.purpose | (.[0:1] | ascii_upcase) + .[1:])\n\n"
    + "`POST <SUPABASE_URL>/rest/v1/rpc/\($fn.name)`\n\n"
    + (if ($fn.args | length) == 0 then "Parameters: none. Send `{}`.\n\n"
       else "| Parameter | Type | Required |\n|---|---|---|\n"
            + ($fn.args | map("| `\(.name)` | `\(.type)` | \(if .required then "yes" else "no" end) |") | join("\n"))
            + "\n\n" end)
    + "Inputs: \($p.inputs)\n\n"
    + (if $p.returns != null then "Returns: \($p.returns)\n\n" else "" end)
    + (if $p.errors != null then "Errors: \($p.errors)\n\n"
       else "Always raises: \($p.raises)\n\n" end)
    + "Required parameters as a JSON skeleton (the Inputs line says what else a call needs, for example a non-empty `changes`):\n\n```json\n"
    + (if ($fn.args | map(select(.required)) | length) == 0 then "{}"
       else "{ " + ($fn.args | map(select(.required)) | map("\"\(.name)\": \(placeholder)") | join(", ")) + " }" end)
    + "\n```\n";

. as $all
| "<!-- Generated by scripts/api-reference.sh from the api_v1 function comments. Do not edit; change the COMMENT in the migration and regenerate. -->\n\n"
  + "# API v1 operation reference\n\n"
  + "Generated from the database: one section per function in the `api_v1` schema, with the text of its comment. "
  + "Conventions (URL, headers, sign-in, envelopes, errors, pagination, budgets) are in [README.md](README.md); a worked seeding walk-through is in [seeding-guide.md](seeding-guide.md).\n\n"
  + "Every operation is `POST <SUPABASE_URL>/rest/v1/rpc/<name>` with a JSON object of named parameters, "
  + "the headers `apikey: <ANON_KEY>`, `Authorization: Bearer <ACCESS_TOKEN>`, `Content-Type: application/json`, "
  + "and `Content-Profile: api_v1` and `Accept-Profile: api_v1`. "
  + "Parameters marked not required may be omitted. Unknown parameter names are rejected by the data API before the function runs.\n\n"
  + "## Index\n\n"
  + ([areas[] as $a | ($all | map(select(.name | area == $a))) as $fs | select($fs | length > 0)
      | "**\($a):** " + ($fs | map("[`\(.name)`](#\(.name))") | join(", "))] | join("\n\n"))
  + "\n\n"
  + ([areas[] as $a | ($all | map(select(.name | area == $a))) as $fs | select($fs | length > 0)
      | "## \($a)\n\n" + ($fs | map(section(.)) | join("\n"))] | join("\n"))
'

RENDERED="$(printf '%s' "$CATALOG" | jq -r "$RENDER")"
# jq -r appends one newline; keep exactly one trailing newline.
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT
printf '%s\n' "$RENDERED" | sed -e :a -e '/^\n*$/{$d;N;ba' -e '}' > "$TMP"

if [ "$CHECK" -eq 1 ]; then
  if diff -u "$OUT" "$TMP" >/dev/null 2>&1; then
    echo "api-reference: $OUT matches the database"
    exit 0
  fi
  echo "api-reference: $OUT is stale versus the database; run scripts/api-reference.sh and commit the result" >&2
  diff -u "$OUT" "$TMP" | head -40 >&2 || true
  exit 1
fi

mkdir -p "$(dirname "$OUT")"
cp "$TMP" "$OUT"
echo "api-reference: wrote $OUT ($(grep -c '^### ' "$OUT") operations)"
