#!/usr/bin/env bash
# Bring a FRESH SANDBOX (cloud agent, new clone, wiped machine) to the point where BOTH review
# batteries can run: code review needs only the diff, but the DESIGN review needs a RENDERED,
# LOGGED-IN app — and a clone alone cannot log in, because mos-app/.env* are gitignored.
#
# This script is the piping for that gap. Idempotent: safe to re-run, never clobbers an existing
# .env (the owner's machine has real values in it).
#
# Usage:  bash scripts/cloud-agent-bootstrap.sh
#
# ponytail: no flags, no config. If you need a non-default port or a hosted backend, do it by hand
# and say so in the ledger — that's rare enough not to earn options here.
set -euo pipefail

cd "$(dirname "$0")/.."
REPO="$PWD"
APP="$REPO/mos-app"

say() { printf '\n\033[1m==> %s\033[0m\n' "$1"; }
die() { printf '\n\033[31mFAIL: %s\033[0m\n' "$1" >&2; exit 1; }

# ── 0. Preconditions ────────────────────────────────────────────────────────────
say "Checking tools"
command -v docker >/dev/null || die "no docker. The local Supabase stack needs it.
  Without Docker you CANNOT run the design review in-sandbox. Options, in order:
    1. Enable Docker in this runtime (preferred — everything works).
    2. Point VITE_SUPABASE_URL/ANON_KEY at a SEPARATE cloud Supabase project.
       NEVER at staging: it holds real business data and a design review clicks buttons.
    3. Stop the step at 'built, review-pending' and say so. Never mark a step done on code
       review alone (docs/plans/CLOUD-AGENT-HANDOFF.md §3)."
docker info >/dev/null 2>&1 || die "docker is installed but not running/reachable."
command -v supabase >/dev/null || die "no supabase CLI. Install: https://github.com/supabase/cli#install-the-cli"
command -v npm >/dev/null || die "no npm. Node 22 expected (see .github/workflows/integration.yml)."

# ── 1. Supabase stack ───────────────────────────────────────────────────────────
# Exclusion list is kept IDENTICAL to .github/workflows/integration.yml on purpose: that list is
# load-bearing and battle-tested (edge-runtime intermittently 502s and flaked a PR). If you add a
# container here, add it there too — a sandbox that differs from CI is a lie about CI.
say "Starting Supabase (excluding containers the app doesn't use)"
if supabase status >/dev/null 2>&1; then
  echo "already running — reusing"
else
  supabase start -x edge-runtime,functions,studio,meta,imgproxy,storage,realtime,vector,analytics
fi

# ── 2. App env — THE actual gap for a fresh clone ────────────────────────────────
# Local stack keys are well-known dev constants (same ones CI injects), but we still never echo
# them: no key text in logs, ever. Write-if-absent so the owner's real .env survives a re-run.
say "Writing app env"
STATUS_ENV="$(supabase status -o env)"
get() { printf '%s\n' "$STATUS_ENV" | grep -E "^$1=" | head -1 | cut -d= -f2- | tr -d '"'; }
API_URL="$(get API_URL)"; ANON_KEY="$(get ANON_KEY)"; SERVICE_ROLE_KEY="$(get SERVICE_ROLE_KEY)"
[ -n "$API_URL" ] && [ -n "$ANON_KEY" ] && [ -n "$SERVICE_ROLE_KEY" ] || die "supabase status returned no keys — is the stack fully up?"

write_env() { # $1 = path
  if [ -f "$1" ]; then
    echo "kept existing $(basename "$1") (not clobbering)"
    return
  fi
  cat > "$1" <<EOF
# Generated by scripts/cloud-agent-bootstrap.sh for the LOCAL ephemeral stack.
# Local dev constants only — never real secrets, never staging. Gitignored.
VITE_SUPABASE_URL=$API_URL
VITE_SUPABASE_ANON_KEY=$ANON_KEY
SUPABASE_SERVICE_ROLE_KEY=$SERVICE_ROLE_KEY
VITE_SHOW_PLAN_BUDGET=true
EOF
  echo "wrote $(basename "$1")"
}
write_env "$APP/.env"      # vite dev server
write_env "$APP/.env.e2e"  # playwright.config.ts reads this for its webServer

# ── 3. Deps + browser ───────────────────────────────────────────────────────────
say "Installing app dependencies"
(cd "$APP" && npm ci)

say "Installing Chromium for Playwright"
(cd "$APP" && npx playwright install --with-deps chromium)

# ── 4. Prove it renders — the design review's precondition ───────────────────────
# ponytail: this asserts the two things that are actually broken on a fresh clone (dev server
# serves the SPA + the auth endpoint answers). It does NOT prove a full login round-trip —
# `npx playwright test` does, and the agent runs that anyway. Ceiling named, not hidden.
say "Verifying the app renders"
(cd "$APP" && npm run dev >/tmp/mos-dev-boot.log 2>&1 & echo $! >/tmp/mos-dev.pid)
trap 'kill "$(cat /tmp/mos-dev.pid 2>/dev/null)" 2>/dev/null || true' EXIT

for i in $(seq 1 60); do
  curl -sf http://localhost:5173/mos/ >/dev/null 2>&1 && break
  [ "$i" = 60 ] && { cat /tmp/mos-dev-boot.log; die "dev server never came up at http://localhost:5173/mos/"; }
  sleep 1
done
echo "dev server: serving /mos/"

curl -sf "$API_URL/auth/v1/health" -H "apikey: $ANON_KEY" >/dev/null || die "Supabase auth unreachable at $API_URL — login (and therefore the design review) will not work."
echo "supabase auth: reachable"

say "READY — both review batteries can run"
cat <<'EOF'
  Design review needs the app up:   cd mos-app && npm run dev    → http://localhost:5173/mos/
    demo login: persona buttons, password Passw0rd!dev
  Mockups to judge against (serve from this repo):
    docs/design-mockups/redesign-mockups-2026-07/            serve-e7.py            → :8766
    docs/design-mockups/redesign-mockups-2026-07/convergence-flows/serve-flows.py   → :8134
  Gates:  cd mos-app && npm run typecheck && npm test && npx playwright test
          supabase test db          (pgTAP — LOCAL stack only, never staging)
          bash scripts/pre-merge-check.sh
  Charter: docs/plans/CLOUD-AGENT-HANDOFF.md   State: docs/plans/AUTONOMOUS-RUN-STATE.md
EOF
