#!/usr/bin/env bash
#
# mcp-catalog.sh — writes supabase/functions/mcp/catalog.ts, the MCP server's operation catalog,
# from the `api_v1` function catalog and the COMMENT on each function in the local database. It is
# the same source as scripts/api-reference.sh (scripts/lib/api-catalog.sql), so the tool list and
# the API reference cannot drift apart.
#
#   scripts/mcp-catalog.sh            regenerate supabase/functions/mcp/catalog.ts
#   scripts/mcp-catalog.sh --check    fail (exit 1) if the committed file differs from a fresh render
#   scripts/mcp-catalog.sh --out F    write to F instead
#
# Reads the running local stack (docker exec into the project's database container). Environment:
#   MOS_DB_CONTAINER       database container name (default: supabase_db_<project_id> from config.toml)
#   MOS_API_CATALOG_JSON   render from this catalog file and skip the database (self-test)
#
# A function whose comment does not follow "Purpose: … Inputs: … [Returns: …] Errors: …" (or
# "Always raises: …" in place of Errors) fails the run: an undocumented operation cannot become a tool.
set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$REPO/supabase/functions/mcp/catalog.ts"
CHECK=0
while [ "$#" -gt 0 ]; do
  case "$1" in
    --check) CHECK=1 ;;
    --out) OUT="${2:?--out needs a path}"; shift ;;
    *) echo "usage: $0 [--check] [--out FILE]" >&2; exit 2 ;;
  esac
  shift
done

command -v jq >/dev/null || { echo "mcp-catalog: jq is required" >&2; exit 2; }

if [ -n "${MOS_API_CATALOG_JSON:-}" ]; then
  CATALOG="$(cat "$MOS_API_CATALOG_JSON")"
else
  PROJECT_ID="$(sed -n 's/^project_id *= *"\(.*\)"/\1/p' "$REPO/supabase/config.toml" | head -1)"
  CONTAINER="${MOS_DB_CONTAINER:-supabase_db_${PROJECT_ID}}"
  CATALOG="$(docker exec -i "$CONTAINER" psql -U postgres -d postgres -At -v ON_ERROR_STOP=1 -f - < "$REPO/scripts/lib/api-catalog.sql")" \
    || { echo "mcp-catalog: could not read the catalog from container $CONTAINER (is the local stack up?)" >&2; exit 2; }
fi

[ "$(printf '%s' "$CATALOG" | jq 'length')" -gt 0 ] \
  || { echo "mcp-catalog: the catalog holds no api_v1 functions; refusing to write an empty catalog" >&2; exit 2; }

RENDER='
def parse:
  (.comment // "") as $c
  | ($c | capture("^Purpose: (?<purpose>.*?) Inputs: (?<inputs>.*?)(?: Returns: (?<returns>.*?))?(?: Errors: (?<errors>.*?)| Always raises: (?<raises>.*?))$"))
  // error("api_v1." + .name + ": comment does not follow Purpose / Inputs / [Returns] / Errors");
map(
  . as $f | ($f | parse) as $p
  | { name: $f.name,
      purpose: $p.purpose,
      inputs: $p.inputs,
      returns: $p.returns,
      errors: (if $p.errors != null then $p.errors else "Always raises: " + $p.raises end),
      args: $f.args }
  | if .returns == null then del(.returns) else . end)
'

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT
{
  printf '%s\n' '// Generated by scripts/mcp-catalog.sh from the api_v1 function comments. Do not edit; change the'
  printf '%s\n' '// COMMENT in the migration and regenerate. One entry per api_v1 operation: the MCP server offers'
  printf '%s\n' '// exactly these as tools.'
  printf '%s\n\n' "import type { ApiV1Operation } from './types.ts'"
  printf 'export const API_V1_CATALOG: readonly ApiV1Operation[] = '
  printf '%s' "$CATALOG" | jq --indent 2 "$RENDER"
} > "$TMP"

if [ "$CHECK" -eq 1 ]; then
  if diff -u "$OUT" "$TMP" >/dev/null 2>&1; then
    echo "mcp-catalog: $OUT matches the database"
    exit 0
  fi
  echo "mcp-catalog: $OUT is stale versus the database; run scripts/mcp-catalog.sh and commit the result" >&2
  diff -u "$OUT" "$TMP" | head -40 >&2 || true
  exit 1
fi

mkdir -p "$(dirname "$OUT")"
cp "$TMP" "$OUT"
echo "mcp-catalog: wrote $OUT ($(printf '%s' "$CATALOG" | jq 'length') operations)"
