// createTaskRecordAdapter — projects the REAL Task model (mos.tasks / TaskDetail) into
// the shared RecordViewer grammar (V3 Issue 5, plan Task 4). A Task stays a Task: this
// adapter does not convert the row into a universal record, and it keeps every Task
// distinction the domain owns.
//
// Vocabulary is BINDING (CONTEXT.md): the legacy storage columns responsible_person_id /
// accountable_person_id are displayed as Person in charge (PIC) and Supervisor. The
// viewer NEVER exposes Responsible / Accountable / RACI / Consulted / Informed. Business
// Unit and Team are DISTINCT fields; a legacy task without team_id remains an honest
// "Team not assigned yet (data migration)" state — never a BU relabel.
//
// The one place the legacy person-storage mismatch is translated is the TaskSurface DAL
// switch (deferred host wiring); this adapter is entirely domain-facing.
import type { ReactNode } from 'react'
import type { TaskDetail } from '@/lib/db/tasks'
import type { TaskListRow, TaskStatus } from '@/lib/db/tasks.types'
import type { PersonOption, BusinessUnitOption } from '@/lib/db/directory'
import type { ObjectiveRow } from '@/lib/db/objectives'
import type { WorkLineRow } from '@/lib/db/work-lines'
import { canEdit, canArchive, picOptions } from './task-permissions'
import { RecordFieldList } from '@/components/records/record-viewer'
import type {
  RecordAction,
  RecordContentSlot,
  RecordFieldOption,
  RecordFieldSpec,
  RecordHeaderContextItem,
  RecordMetadataSection,
  RecordValue,
  RecordViewerAdapter,
} from '@/components/records/record-viewer.types'

export type TaskViewerFieldKey =
  | 'title'
  | 'description'
  | 'dueDate'
  | 'team'
  | 'businessUnit'
  | 'pic'
  | 'supervisor'
  | 'projectProcess'
  | 'objective'

type TaskClosureFields = TaskListRow & {
  team_id?: string | null
  completed_at?: string | null
}

export interface TaskTeamView {
  id: string
  label: string
  businessUnitLabel?: string
}

export type TaskRelatedRecord = { kind: 'objective' | 'work-line'; id: string }

export interface TaskRecordAdapterInput {
  detail: TaskDetail
  viewerId: string
  /** #742 AC-061 (delta): the viewer's already-loaded downline person ids — the raw fact
   *  canEdit/canArchive derive "viewer is above the PIC" from. The helper owns that derivation;
   *  this adapter never receives a viewer-global isManager. Empty for an unauthenticated viewer. */
  downlineIds: readonly string[]
  people: readonly PersonOption[]
  businessUnits: readonly BusinessUnitOption[]
  objectives?: readonly ObjectiveRow[]
  linkedObjective?: ObjectiveRow | null
  workLines?: readonly WorkLineRow[]
  labels?: TaskFieldLabels
  /** Locale-resolved chrome labels for the full record (LocaleParityContract). */
  recordLabels?: Partial<TaskRecordLabels>
  /**
   * Only a real task.team_id lookup may populate this value. Omit or pass null while
   * the current mos.tasks row has no team_id (Issue 8 BU→Team re-home dependency).
   */
  team?: TaskTeamView | null
  /** The viewer's effective Teams; Team editing is scoped to this list, never to BU rows. */
  teamOptions?: readonly TaskTeamView[]
  /**
   * The generating `mos.process_task_defs.title` for a task materialized by
   * `mos.spawn_process_run` / `mos.resolve_pending_task` (ADR-0051 Step 6, real
   * `task.generated_from_task_def_id`). Omit or pass null for a hand-created (ad hoc)
   * task, or while the label lookup hasn't resolved yet — the "Generated by" chip is
   * conditional (E7 record grammar), never a fabricated placeholder.
   */
  generatedFromLabel?: string | null
  /**
   * Formats an ISO `YYYY-MM-DD` into the record's DISPLAY string. The live TaskSurface passes the
   * SAME `task-formatters.formatDate` family the table row uses (V3 owner-eyes item 2) so a record's
   * Due reads "Wed 8 Jul", never the raw ISO "2026-07-08". Omitted → the raw ISO is shown (keeps the
   * adapter's own unit tests literal). The field's `value` stays the ISO string for the edit control.
   */
  formatDate?: (iso: string) => string
  /** Formats the immutable creator date; omitted keeps a stable ISO date for adapter tests. */
  formatCreatedAt?: (iso: string) => string
  /** Formats a relative activity/completion age for the pinned header. */
  formatAge?: (iso: string) => string
  onUpdateField: (field: TaskViewerFieldKey, value: string | null) => Promise<void>
  onUpdateStatus: (next: TaskStatus) => Promise<void>
  onArchive: () => Promise<void>
  onUnarchive: () => Promise<void>
  onOpenRelated?: (relation: TaskRelatedRecord) => void
}

const TASK_STATUSES: readonly TaskStatus[] = ['Open', 'In Progress', 'Blocked', 'Done']
const TEAM_UNASSIGNED = 'Team not assigned yet (data migration)'

const EVENT_LABELS: Record<string, string> = {
  created: 'Created',
  status_changed: 'Status changed',
  field_edited: 'Field edited',
  raci_edited: 'Ownership edited',
  archived: 'Archived',
  unarchived: 'Unarchived',
}

function personOptions(people: readonly PersonOption[]): RecordFieldOption[] {
  return people.map((p) => ({ value: p.id, label: p.full_name }))
}
function personName(people: readonly PersonOption[], id: string | null): string {
  return people.find((p) => p.id === id)?.full_name ?? 'Unassigned'
}
function firstName(name: string): string {
  return name.trim().split(/\s+/)[0] || name
}
function buName(bus: readonly BusinessUnitOption[], id: string): string {
  return bus.find((b) => b.id === id)?.name ?? id
}

/** Wrap a field spec with the shared editable policy.
 *
 *  R4 (owner review r2): an editable-by-design field that the current viewer can't edit shows NO
 *  per-field reason — just its value, read-only, with no edit affordance. The single whole-record
 *  read-only note (why the viewer can't edit) is carried ONCE by RecordViewer's footer from
 *  adapter.permission.reason. Stamping the same "you can't edit this task" line onto every field
 *  was the repetitive noise the owner flagged: a wall of identical reasons with no per-field intent.
 *  A genuinely field-specific reason (e.g. the honest Team-migration state, teamOwnershipField)
 *  still sets its own readOnlyReason directly; this shared wrapper simply never adds a blanket one. */
function editableSpec(
  editable: boolean,
  spec: Omit<RecordFieldSpec, 'editable'>,
): RecordFieldSpec {
  return { ...spec, editable }
}

/** i18n-able labels for the shared Task field builders. Defaults are English so the full
 *  createTaskRecordAdapter and the adapter's own unit tests keep their literals; the LIVE
 *  TaskSurface passes locale-resolved strings (LocaleParityContract). */
export interface TaskFieldLabels {
  businessUnit: string
  businessUnitDerived: string
  pic: string
  supervisor: string
  team: string
  teamUnassigned: string
  teamFromRecord: string
  teamMigration: string
  dueDate: string
  createdBy: string
  activity: string
}

/** i18n-able labels for the FULL Task record adapter's chrome — section titles, the
 *  catalog/provenance field labels, lifecycle actions, the type eyebrow, and the read-only
 *  reasons. Defaults are English so the adapter's own unit tests keep their literals; the
 *  LIVE TaskSurface passes locale-resolved strings (LocaleParityContract). The ownership
 *  landmark in particular must read "Task ownership" (the oracle's accessible name), NOT a
 *  bare "Ownership". */
export interface TaskRecordLabels {
  typeLabel: string
  ownershipSection: string
  statusSection: string
  detailsSection: string
  /** Content-first anatomy (OD-REDESIGN-90 §2.3): the Relations region heading. */
  relatedSection: string
  statusField: string
  /** DO-13/I18N-2 — the record-door status pill + picker options localize the enum text
   *  (the pill's semantic hue stays keyed to the raw `value`, see record-field.tsx). */
  statusOpen: string
  statusInProgress: string
  statusBlocked: string
  statusDone: string
  descriptionField: string
  projectProcessField: string
  objectiveField: string
  sourceField: string
  /** Visible null-indicator for a read-only catalog field with no value (em dash). */
  noneMarker: string
  markComplete: string
  /** Lifecycle-aware secondary action shown IN PLACE of markComplete on an already-Done task
   *  (owner-eyes item 10) — sending the task back to the active pool. */
  reopen: string
  archive: string
  unarchive: string
  readOnlyArchived: string
  readOnlyNoPermission: string
  /** E7 record grammar — conditional chip naming the generating process task definition;
   *  rendered only when the real `generated_from_task_def_id` provenance resolves a label. */
  generatedByField: string
  noObjective?: string
  adHoc: string
  completedAtField: string
}

const DEFAULT_TASK_RECORD_LABELS: TaskRecordLabels = {
  typeLabel: 'Task',
  ownershipSection: 'Task ownership',
  statusSection: 'Status & Timing',
  detailsSection: 'Task details',
  relatedSection: 'Related',
  statusField: 'Status',
  statusOpen: 'Open',
  statusInProgress: 'In Progress',
  statusBlocked: 'Blocked',
  statusDone: 'Done',
  descriptionField: 'Description',
  projectProcessField: 'Project/Process',
  objectiveField: 'Objective',
  sourceField: 'Source',
  noneMarker: '—',
  markComplete: 'Mark complete',
  reopen: 'Reopen',
  archive: 'Archive task',
  unarchive: 'Unarchive',
  readOnlyArchived: 'This task is archived',
  // DO-23(b) (census R2 task-record P3-2): the note names the problem AND the recovery.
  readOnlyNoPermission: "You don't have permission to edit this task. Ask a manager or admin to change its ownership.",
  generatedByField: 'Generated by',
  noObjective: 'No Objective',
  adHoc: 'Ad hoc',
  completedAtField: 'Completed',
}

const DEFAULT_TASK_FIELD_LABELS: TaskFieldLabels = {
  businessUnit: 'Business Unit',
  businessUnitDerived: 'BU',
  pic: 'Person in charge (PIC)',
  supervisor: 'Supervisor',
  team: 'Team',
  teamUnassigned: TEAM_UNASSIGNED,
  teamFromRecord: 'Team is set from the task record',
  teamMigration: 'No team is assigned to this task yet (data migration).',
  dueDate: 'Due date',
  createdBy: 'Created by',
  activity: 'Activity',
}

/** The honest Team field spec — Business Unit is NEVER relabelled Team; a real task.team_id lookup
 *  fills Team, otherwise it shows the honest migration state. Options are limited to the viewer's
 *  effective Teams, so the field never manufactures a Team from a BU. */
export function teamOwnershipField(
  team: TaskTeamView | null | undefined,
  labels: TaskFieldLabels = DEFAULT_TASK_FIELD_LABELS,
  editable = false,
  teamOptions: readonly TaskTeamView[] = [],
): RecordFieldSpec {
  const options: RecordFieldOption[] = [
    { value: '', label: labels.teamUnassigned },
    ...teamOptions
      .filter((option) => option.id !== team?.id)
      .map((option) => ({ value: option.id, label: option.label })),
  ]
  const canPick = editable && teamOptions.length > 0
  return {
    key: 'team',
    label: labels.team,
    control: 'team',
    value: team?.id ?? null,
    displayValue: team?.label ?? labels.teamUnassigned,
    subline: `${labels.businessUnitDerived}: ${team?.businessUnitLabel ?? ''}`.replace(/: $/, ''),
    options: canPick ? options : undefined,
    editable: canPick,
    readOnlyReason: canPick ? undefined : team ? labels.teamFromRecord : labels.teamMigration,
  }
}

/** The Task ownership fields — Team, PIC, Supervisor, Created by — shared by the full adapter. */
function ownershipFields(
  task: TaskClosureFields,
  editable: boolean,
  viewerId: string,
  downlineIds: readonly string[],
  people: readonly PersonOption[],
  businessUnits: readonly BusinessUnitOption[],
  team: TaskTeamView | null | undefined,
  teamOptions: readonly TaskTeamView[],
  createdAt: string,
  formatCreatedAt: (iso: string) => string,
  labels: TaskFieldLabels = DEFAULT_TASK_FIELD_LABELS,
): RecordFieldSpec[] {
  return [
    teamOwnershipField(team, labels, editable, teamOptions),
    {
      key: 'businessUnit',
      label: labels.businessUnit,
      control: 'text',
      value: task.business_unit_id,
      displayValue: buName(businessUnits, task.business_unit_id),
      editable: false,
      readOnlyReason: undefined,
    },
    editableSpec(editable, {
      key: 'pic',
      label: labels.pic,
      control: 'person',
      value: task.responsible_person_id,
      displayValue: personName(people, task.responsible_person_id),
      // Same contract as the inline picker (#742): the record's PIC picker offers the WRITER's
      // self + downline — the only values the DB's PIC-value clause accepts from this writer.
      options: personOptions(picOptions(viewerId, people, downlineIds)),
    }),
    editableSpec(editable, {
      key: 'supervisor',
      label: labels.supervisor,
      control: 'person',
      value: task.accountable_person_id,
      displayValue: personName(people, task.accountable_person_id),
      options: personOptions(people),
    }),
    {
      key: 'createdBy',
      label: labels.createdBy,
      control: 'text',
      value: task.created_by,
      displayValue: `${firstName(personName(people, task.created_by))} · ${formatCreatedAt(createdAt)}`,
      editable: false,
      readOnlyReason: undefined,
    },
  ]
}

/** The Task due-date field (a text-like date control that holds a draft), shared by both adapters.
 *  `formatDate` renders the value-first DISPLAY string (item 2 — same formatter family as the table);
 *  `value` stays the raw ISO the edit control writes/reads. */
function dueField(
  task: Pick<TaskListRow, 'due_date'>,
  editable: boolean,
  label: string = DEFAULT_TASK_FIELD_LABELS.dueDate,
  formatDate: (iso: string) => string = (iso) => iso,
): RecordFieldSpec {
  return editableSpec(editable, {
    key: 'dueDate',
    label,
    control: 'date',
    value: task.due_date,
    displayValue: task.due_date ? formatDate(task.due_date) : 'No due date',
  })
}

/** Dispatch a domain-facing field commit to the correct DAL callback. Status is the
 *  one non-`updateTaskFields` field; every other key flows through onUpdateField. */
export function createTaskFieldCommit(
  input: Pick<TaskRecordAdapterInput, 'onUpdateField' | 'onUpdateStatus'>,
): (key: string, value: RecordValue) => Promise<void> {
  return async (key, value) => {
    if (key === 'status') {
      await input.onUpdateStatus(value as TaskStatus)
      return
    }
    await input.onUpdateField(key as TaskViewerFieldKey, value === null ? null : String(value))
  }
}

/** Locale-facing text for a status enum (DO-13/I18N-2) — the raw value stays the commit payload. */
function statusLabel(s: TaskStatus, L: TaskRecordLabels): string {
  return s === 'Open' ? L.statusOpen
    : s === 'In Progress' ? L.statusInProgress
    : s === 'Blocked' ? L.statusBlocked
    : L.statusDone
}

export function createTaskRecordAdapter(input: TaskRecordAdapterInput): RecordViewerAdapter {
  const {
    detail,
    viewerId,
    downlineIds,
    people,
    businessUnits,
    objectives = [],
    workLines = [],
    team,
    teamOptions = [],
  } = input
  const formatDate = input.formatDate ?? ((iso: string) => iso)
  const formatCreatedAt = input.formatCreatedAt ?? ((iso: string) => iso.slice(0, 10))
  const formatAge = input.formatAge ?? ((iso: string) => formatCreatedAt(iso))
  const labels = input.labels ?? DEFAULT_TASK_FIELD_LABELS
  const L = { ...DEFAULT_TASK_RECORD_LABELS, ...input.recordLabels }
  const task = detail.task as TaskClosureFields
  const archived = task.archived_at !== null
  const editable = canEdit(task, viewerId, downlineIds) && !archived
  const canArchiveTask = canArchive(task, viewerId, downlineIds)

  // The ONE whole-record read-only note (why the viewer can't edit) — surfaced once by
  // RecordViewer's footer via `permission.reason` below. It is NOT stamped onto every field
  // (R4 — see editableSpec): a wall of identical per-field reasons was the noise the owner flagged.
  const readOnlyReason = archived ? L.readOnlyArchived : L.readOnlyNoPermission

  const editSpec = (spec: Omit<RecordFieldSpec, 'editable'>): RecordFieldSpec => ({
    ...spec,
    editable,
  })

  // Content-first document anatomy (OD-REDESIGN-90 §2.2, FR-ANAT-009): the Task leads with its
  // OWN content — Title (identity h1) + Description — then Ownership → Relations → Checklist →
  // Activity. The regions are packed into ORDERED content slots so the content leads without
  // flipping record-viewer.tsx's shared region order (which would endanger every other consumer
  // and paint the metadata region before content anyway). E7's calm-document intent is preserved;
  // only the ORDER obeys LAW-1 (content leads) / LAW-2 (Status + Due ride with the content).
  const workLine = workLines.find((row) => row.id === task.work_line_id) ?? null
  const workLineName = workLine?.name ?? null
  const objectiveName = objectives.find((row) => row.id === task.objective_id)?.name
    ?? (input.linkedObjective?.id === task.objective_id ? input.linkedObjective.name : null)
  // R5 (owner review r2, owner-ratified DELETE): the derived Classification row was removed as a
  // fossil — it duplicated what the record already carries ("Generated" ⇒ the Generated-by chip,
  // "Project" ⇒ the Project/Process relation row, "Ad hoc" ⇒ the absence of both). It only existed
  // because the E7 mockup drew it (a quality floor, not a data spec), so no information is lost.
  const sourceDisplay = workLineName ?? objectiveName
  const sourceHref = workLineName
    ? `/work/projects/${task.work_line_id}`
    : objectiveName
      ? `/work/objectives/${task.objective_id}`
      : undefined
  const teamWithDerivedBu = team
    ? { ...team, businessUnitLabel: team.businessUnitLabel ?? buName(businessUnits, task.business_unit_id) }
    : null

  // 1. Content (LEADS) — Description prose directly beneath the identity title; Status pill + Due
  //    ride with it (LAW-2 — urgency adjacent to the content it qualifies, not a downstream block).
  const titleField = editSpec({
    key: 'title',
    label: 'title',
    control: 'text',
    value: task.title,
    displayValue: task.title,
  })
  const due = dueField(task, editable, labels.dueDate, formatDate)
  const headerContext: RecordHeaderContextItem[] = [
    {
      key: 'team',
      label: labels.team,
      displayValue: teamWithDerivedBu?.label ?? labels.teamUnassigned,
    },
    {
      key: 'pic',
      label: labels.pic,
      displayValue: personName(people, task.responsible_person_id),
    },
    {
      key: 'supervisor',
      label: labels.supervisor,
      displayValue: personName(people, task.accountable_person_id),
    },
    ...(task.due_date ? [{
      key: 'dueDate',
      label: labels.dueDate,
      displayValue: due.displayValue,
    }] : []),
    {
      key: 'activity',
      label: labels.activity,
      displayValue: formatAge(task.last_activity_at),
    },
    ...(task.status === 'Done' && task.completed_at ? [{
      key: 'completedAt',
      label: L.completedAtField,
      displayValue: formatAge(task.completed_at),
    }] : []),
  ]
  const content: RecordMetadataSection = {
    id: 'content',
    label: L.detailsSection,
    fields: [
      editSpec({
        key: 'description',
        label: L.descriptionField,
        control: 'textarea',
        value: task.description,
        displayValue: task.description ?? L.noneMarker,
      }),
      editSpec({
        key: 'status',
        label: L.statusField,
        control: 'status',
        value: task.status,
        displayValue: statusLabel(task.status, L),
        options: TASK_STATUSES.map((s) => ({ value: s, label: statusLabel(s, L) })),
      }),
      due,
    ],
  }

  // 2. Ownership — Team · derived BU · PIC · Supervisor · Created by. Team is the canonical
  //    editable owner; legacy BU remains visible but read-only and is never used as a Team.
  const ownership: RecordMetadataSection = {
    id: 'ownership',
    label: L.ownershipSection,
    fields: ownershipFields(
      task,
      editable,
      viewerId,
      downlineIds,
      people,
      businessUnits,
      teamWithDerivedBu,
      teamOptions,
      task.created_at,
      formatCreatedAt,
      labels,
    ),
  }

  // 3. Relations — Project/Process · Objective (settable navigational links) · Generated-by ·
  //    Source (read-only provenance), each rendered WHERE the datum exists. Source/Generated-by
  //    carry no per-field reason (LAW-6 / F3 — one whole-record note only).
  const relations: RecordMetadataSection = {
    id: 'relations',
    label: L.relatedSection,
    fields: [
      editSpec({
        key: 'projectProcess',
        label: L.projectProcessField,
        control: 'relation',
        value: task.work_line_id,
        displayValue: workLineName ?? L.adHoc,
        options: [{ value: '', label: L.noneMarker }, ...workLines.map((row) => ({ value: row.id, label: row.name }))],
        href: workLineName ? `/work/projects/${task.work_line_id}` : undefined,
        onOpen: workLineName && task.work_line_id && input.onOpenRelated ? () => input.onOpenRelated?.({ kind: 'work-line', id: task.work_line_id! }) : undefined,
      }),
      editSpec({
        key: 'objective',
        label: L.objectiveField,
        control: 'relation',
        value: task.objective_id,
        displayValue: objectiveName ?? (L.noObjective ?? L.adHoc),
        options: [{ value: '', label: L.noneMarker }, ...objectives.map((row) => ({ value: row.id, label: row.name }))],
        href: objectiveName ? `/work/objectives/${task.objective_id}` : undefined,
        onOpen: objectiveName && task.objective_id && input.onOpenRelated ? () => input.onOpenRelated?.({ kind: 'objective', id: task.objective_id! }) : undefined,
      }),
      // Conditional (E7 record grammar) — rendered only when the real generating task
      // definition resolved a label; a hand-created (ad hoc) task carries no such chip.
      ...(input.generatedFromLabel
        ? [{
            key: 'generatedFrom',
            label: L.generatedByField,
            control: 'text' as const,
            value: input.generatedFromLabel,
            displayValue: input.generatedFromLabel,
            editable: false,
            readOnlyReason: undefined,
          }]
        : []),
      // Source/provenance — always present so an unlinked hand-created Task reads as a state,
      // while a resolved parent is a direct link chip rather than a dead text label.
      {
        key: 'source',
        label: L.sourceField,
        control: 'text' as const,
        value: task.work_line_id ?? task.objective_id ?? null,
        displayValue: sourceDisplay ?? L.adHoc,
        href: sourceHref,
        onOpen: sourceHref && input.onOpenRelated ? () => input.onOpenRelated?.(task.work_line_id ? { kind: 'work-line', id: task.work_line_id } : { kind: 'objective', id: task.objective_id! }) : undefined,
        editable: false,
        readOnlyReason: undefined,
      },
    ],
  }

  const actions: RecordAction[] = []
  const allowedActionIds: string[] = []
  if (archived) {
    if (canArchiveTask) {
      actions.push({ id: 'unarchive', label: L.unarchive, intent: 'secondary', run: input.onUnarchive })
      allowedActionIds.push('unarchive')
    }
  } else {
    if (editable) {
      // Lifecycle-aware lead action (owner-eyes item 10): a Task whose status is already Done must
      // NOT offer a dead-end "Mark complete" primary. Reopening is a supported transition (the Status
      // control freely moves Done → any state), so a Done task instead offers a quiet "Reopen"
      // secondary that returns it to the active pool; every other state keeps "Mark complete".
      // onUpdateStatus RE-THROWS on failure (so the Status FIELD surfaces its visible error/retry).
      // A lifecycle-button trigger is fire-and-forget (`void action.run()` in RecordViewer), so the
      // button swallows the rejection here — the optimistic rollback + sr-only announce it already
      // performs is the button's feedback; without this catch a failed click is an unhandled rejection.
      if (task.status === 'Done') {
        actions.push({
          id: 'reopen',
          label: L.reopen,
          intent: 'secondary',
          run: async () => { try { await input.onUpdateStatus('In Progress') } catch { /* surfaced via optimistic rollback */ } },
        })
        allowedActionIds.push('reopen')
      } else {
        actions.push({
          id: 'complete',
          label: L.markComplete,
          intent: 'primary',
          run: async () => { try { await input.onUpdateStatus('Done') } catch { /* surfaced via optimistic rollback */ } },
        })
        allowedActionIds.push('complete')
      }
    }
    if (canArchiveTask) {
      actions.push({ id: 'archive', label: L.archive, intent: 'secondary', run: input.onArchive })
      allowedActionIds.push('archive')
    }
  }

  const headerActionIds = actions
    .filter((action) => action.id === 'complete' || action.id === 'reopen')
    .map((action) => action.id)
  const headerOverflowActionIds = actions
    .filter((action) => action.id === 'archive' || action.id === 'unarchive')
    .map((action) => action.id)

  // Each field section becomes an ordered CONTENT slot: its specs stay inspectable via `section`
  // and it renders through the shared RecordFieldList wired to the slot's field-commit seam — so a
  // relocated field keeps the exact value-first grammar, Escape isolation, and dirty-guard it had
  // in the metadata region. checklist + activity are the trailing content/audit regions; the live
  // TaskSurface overrides them with the interactive checklist + activity/comments composition.
  const contentSlots: RecordContentSlot[] = [
    fieldSectionSlot(content),
    fieldSectionSlot(ownership),
    fieldSectionSlot(relations),
    { id: 'checklist', label: 'Checklist', render: () => renderChecklist(detail) },
    { id: 'activity', label: 'Activity', render: () => renderActivity(detail) },
  ]

  return {
    kind: 'task',
    id: task.id,
    title: task.title,
    typeLabel: L.typeLabel,
    headerFields: [titleField, content.fields.find((field) => field.key === 'status')!],
    headerContext,
    headerActionIds,
    headerOverflowActionIds,
    metadata: [],
    relations: [],
    contentSlots,
    activity: [],
    actions,
    permission: {
      readOnly: !editable,
      reason: editable ? undefined : readOnlyReason,
      allowedActionIds,
    },
    state: 'ready',
  }
}

/** Wrap a Task field section as an ordered content slot (content-first anatomy): the section
 *  specs are carried as DATA so the adapter stays inspectable, while `render` produces the same
 *  value-first RecordField markup the metadata region emits — wired through the slot's commit seam. */
function fieldSectionSlot(section: RecordMetadataSection): RecordContentSlot {
  return {
    id: section.id,
    label: section.label,
    section,
    render: (ctx) => (
      <RecordFieldList
        section={section}
        onCommitField={ctx.onCommitField}
        onDirtyChange={ctx.onDirtyChange}
        fieldCommitsFrozen={ctx.fieldCommitsFrozen}
        headingLevel={ctx.headingLevel}
        excludeKeys={section.id === 'content' ? ['status'] : []}
      />
    ),
  }
}

/** The default Activity (audit) region — the event log, last and quiet. The live TaskSurface
 *  overrides this slot with the interactive Activity + comment thread; this default keeps the
 *  adapter self-renderable (its own unit test) without a raw old→new diff dump (LAW-5 / F4). */
function renderActivity(detail: TaskDetail): ReactNode {
  if (detail.events.length === 0) {
    return <p className="record-activity__empty">No activity yet.</p>
  }
  return (
    <ul className="record-viewer__activity">
      {detail.events.map((e) => (
        <li key={e.id} className="record-viewer__activity-item">
          <span>{EVENT_LABELS[e.event_type] ?? e.event_type}</span>
          <time dateTime={e.created_at} className="record-viewer__activity-time">
            {e.created_at}
          </time>
        </li>
      ))}
    </ul>
  )
}

// Checklist is Task content that inherits the parent Task's PIC/Supervisor — it has NO
// independent ownership, status, Team, or due-date controls (plan Task 4).
function renderChecklist(detail: TaskDetail): ReactNode {
  if (detail.checklist.length === 0) {
    return <p className="record-checklist__empty">No checklist items.</p>
  }
  return (
    <ul className="record-checklist" aria-label="Checklist">
      {detail.checklist.map((item) => (
        <li key={item.id} className="record-checklist__item">
          <input type="checkbox" checked={item.is_done} disabled readOnly aria-label={item.label} />
          <span>{item.label}</span>
        </li>
      ))}
    </ul>
  )
}
