// createTaskRecordAdapter — projects the REAL Task model (mos.tasks / TaskDetail) into
// the shared RecordViewer grammar (V3 Issue 5, plan Task 4). A Task stays a Task: this
// adapter does not convert the row into a universal record, and it keeps every Task
// distinction the domain owns.
//
// Vocabulary is BINDING (CONTEXT.md): the legacy storage columns responsible_person_id /
// accountable_person_id are displayed as Person in charge (PIC) and Supervisor. The
// viewer NEVER exposes Responsible / Accountable / RACI / Consulted / Informed. Business
// Unit and Team are DISTINCT fields; while mos.tasks has no team_id the Team field is an
// honest "Team not assigned yet (data migration)" read-only state — never a BU relabel.
// The real Team-backed field/write path is the Issue 8 BU→Team re-home dependency.
//
// The one place the legacy person-storage mismatch is translated is the TaskSurface DAL
// switch (deferred host wiring); this adapter is entirely domain-facing.
import type { ReactNode } from 'react'
import type { TaskDetail } from '@/lib/db/tasks'
import type { TaskListRow, TaskStatus } from '@/lib/db/tasks.types'
import type { PersonOption, BusinessUnitOption } from '@/lib/db/directory'
import type { ObjectiveRow } from '@/lib/db/objectives'
import type { WorkLineRow } from '@/lib/db/work-lines'
import { canEdit, canArchive, picOptions } from './task-permissions'
import { firstName } from './task-formatters'
import { RecordFieldList } from '@/components/records/record-viewer'
import type {
  RecordAction,
  RecordContentSlot,
  RecordFieldOption,
  RecordFieldSpec,
  RecordMetadataSection,
  RecordRelation,
  RecordValue,
  RecordViewerAdapter,
} from '@/components/records/record-viewer.types'

export type TaskViewerFieldKey =
  | 'title'
  | 'description'
  | 'dueDate'
  | 'businessUnit'
  | 'pic'
  | 'supervisor'
  | 'projectProcess'
  | 'objective'
  // #756 AC-036: Team is the owning editable field — the record commits `team_id` and the
  // DB's same-org + BU-equal guard is authoritative (mos._guard_tasks).
  | 'team'

export interface TaskTeamView {
  id: string
  label: string
}

/** A team the viewer may re-home this task to (AC-036) — the picker is scoped to the writer's
 *  own teams because the DB's team-write RLS refuses everything else, and further filtered to
 *  the task's own BU because a cross-BU pick is rejected by mos._guard_tasks. Callers filter
 *  before handing the list to the adapter; the adapter takes the pre-filtered set as truth. */
export interface ViewerTeamOption {
  id: string
  label: string
  /** The team's business_unit_id — used to render the "BU: <name>" subline beneath the value. */
  businessUnitId: string
}

export interface TaskRecordAdapterInput {
  detail: TaskDetail
  viewerId: string
  /** #742 AC-061 (delta): the viewer's already-loaded downline person ids — the raw fact
   *  canEdit/canArchive derive "viewer is above the PIC" from. The helper owns that derivation;
   *  this adapter never receives a viewer-global isManager. Empty for an unauthenticated viewer. */
  downlineIds: readonly string[]
  people: readonly PersonOption[]
  businessUnits: readonly BusinessUnitOption[]
  objectives?: readonly ObjectiveRow[]
  workLines?: readonly WorkLineRow[]
  labels?: TaskFieldLabels
  /** Locale-resolved chrome labels for the full record (LocaleParityContract). */
  recordLabels?: Partial<TaskRecordLabels>
  /**
   * Only a real task.team_id lookup may populate this value. Omit or pass null while
   * the current mos.tasks row has no team_id (Issue 8 BU→Team re-home dependency).
   */
  team?: TaskTeamView | null
  /**
   * #756 AC-036: the viewer's own teams the Team picker may commit — pre-filtered by the
   * writer's BU (a cross-BU pick is refused by mos._guard_tasks). Empty or omitted means
   * the writer has no eligible team; the Team field then STILL renders (never hidden) but
   * as a read-only "Team not assigned yet" — the honest data-migration state, not a fake
   * value. Providing this list is what makes the Team picker editable in the first place.
   */
  viewerTeams?: readonly ViewerTeamOption[]
  /**
   * The Project/Process Accountable (mos.work_lines.accountable_person_id) — Supervisor
   * inheritance resolves against this (OD-REDESIGN-41, AC-039). The adapter accepts it
   * OPTIONAL: `undefined` means "we don't know yet" (no inheritance hint rendered) and
   * `null` means "the parent has no A" (also no hint). A non-null value opts in only when
   * it equals this task's accountable_person_id — the exact "inherited from …" fact.
   */
  parentAccountablePersonId?: string | null
  /**
   * The generating `mos.process_task_defs.title` for a task materialized by
   * `mos.spawn_process_run` / `mos.resolve_pending_task` (ADR-0051 Step 6, real
   * `task.generated_from_task_def_id`). Omit or pass null for a hand-created (ad hoc)
   * task, or while the label lookup hasn't resolved yet — the "Generated by" chip is
   * conditional (E7 record grammar), never a fabricated placeholder.
   */
  generatedFromLabel?: string | null
  /**
   * #756 AC-042: build a link into the task's parent Project/Process (the Source chip's
   * destination — the record navigates the parent record via the panel stack, OD-REDESIGN-41).
   * The adapter delegates route composition to the caller so an unknown parent kind (a bare
   * Objective) is the caller's job to route or return null. The chip renders only when this
   * returns a non-null href.
   */
  buildSourceHref?: (input: { workLineId: string | null; objectiveId: string | null }) => string | null
  /**
   * Formats an ISO `YYYY-MM-DD` into the record's DISPLAY string. The live TaskSurface passes the
   * SAME `task-formatters.formatDate` family the table row uses (V3 owner-eyes item 2) so a record's
   * Due reads "Wed 8 Jul", never the raw ISO "2026-07-08". Omitted → the raw ISO is shown (keeps the
   * adapter's own unit tests literal). The field's `value` stays the ISO string for the edit control.
   */
  formatDate?: (iso: string) => string
  /** Formats a last-activity ISO timestamp into the meta line's compact age ("5h"); the SAME
   *  formatter family the table row uses. Omitted → the activity-age item is skipped. */
  formatAge?: (iso: string) => string
  onUpdateField: (field: TaskViewerFieldKey, value: string | null) => Promise<void>
  onUpdateStatus: (next: TaskStatus) => Promise<void>
  onArchive: () => Promise<void>
  onUnarchive: () => Promise<void>
  onOpenRelated?: (relation: RecordRelation) => void
}

const TASK_STATUSES: readonly TaskStatus[] = ['Open', 'In Progress', 'Blocked', 'Done']
const TEAM_UNASSIGNED = 'Team not assigned yet (data migration)'

const EVENT_LABELS: Record<string, string> = {
  created: 'Created',
  status_changed: 'Status changed',
  field_edited: 'Field edited',
  raci_edited: 'Ownership edited',
  archived: 'Archived',
  unarchived: 'Unarchived',
}

function personOptions(people: readonly PersonOption[]): RecordFieldOption[] {
  return people.map((p) => ({ value: p.id, label: p.full_name }))
}
function personName(people: readonly PersonOption[], id: string | null, unassigned = 'Unassigned'): string {
  return people.find((p) => p.id === id)?.full_name ?? unassigned
}
/** The pinned-header meta shows a person's FIRST name — but the unassigned marker is not a name
 *  and passes through whole ("Belum ditugaskan", never "Belum": firstName splits on the first
 *  space, which truncated the Bahasa marker to a bare "Belum"). */
function metaShortName(people: readonly PersonOption[], id: string | null, unassigned: string): string {
  const person = people.find((p) => p.id === id)
  return person ? firstName(person.full_name) : unassigned
}
function buName(bus: readonly BusinessUnitOption[], id: string, noneMarker = '—'): string {
  return bus.find((b) => b.id === id)?.name ?? noneMarker
}

/** Wrap a field spec with the shared editable policy.
 *
 *  R4 (owner review r2): an editable-by-design field that the current viewer can't edit shows NO
 *  per-field reason — just its value, read-only, with no edit affordance. The single whole-record
 *  read-only note (why the viewer can't edit) is carried ONCE by RecordViewer's footer from
 *  adapter.permission.reason. Stamping the same "you can't edit this task" line onto every field
 *  was the repetitive noise the owner flagged: a wall of identical reasons with no per-field intent.
 *  A genuinely field-specific reason (e.g. the honest Team-migration state, teamOwnershipField)
 *  still sets its own readOnlyReason directly; this shared wrapper simply never adds a blanket one. */
function editableSpec(
  editable: boolean,
  spec: Omit<RecordFieldSpec, 'editable'>,
): RecordFieldSpec {
  return { ...spec, editable }
}

/** i18n-able labels for the shared Task field builders. Defaults are English so the full
 *  createTaskRecordAdapter and the adapter's own unit tests keep their literals; the LIVE
 *  TaskSurface passes locale-resolved strings (LocaleParityContract). */
export interface TaskFieldLabels {
  businessUnit: string
  pic: string
  supervisor: string
  team: string
  teamUnassigned: string
  teamFromRecord: string
  teamMigration: string
  dueDate: string
  /** #756 AC-036: the "BU: <name>" subline beneath the Team value — a derived fact,
   *  not the editable BU field (which was removed from Ownership). */
  buPrefix: (buName: string) => string
  /** #756 AC-039: the "inherited from <first name>" subline beneath Supervisor when its
   *  value equals the parent Project/Process Accountable. Absent otherwise (no hint). */
  supervisorInherited: (firstName: string) => string
  /** #756 AC-037: the Ownership "Created by <first name> · <date>" line. */
  createdBy: string
  createdByLine: (firstName: string, date: string) => string
  /** #756 AC-038 / DESIGN.md A7: a missing optional relation renders its derived state
   *  word ("Ad hoc"), never "—". Used for Project/Process and Objective. */
  adHoc: string
}

/** i18n-able labels for the FULL Task record adapter's chrome — section titles, the
 *  catalog/provenance field labels, lifecycle actions, the type eyebrow, and the read-only
 *  reasons. Defaults are English so the adapter's own unit tests keep their literals; the
 *  LIVE TaskSurface passes locale-resolved strings (LocaleParityContract). The ownership
 *  landmark in particular must read "Task ownership" (the oracle's accessible name), NOT a
 *  bare "Ownership". */
export interface TaskRecordLabels {
  typeLabel: string
  ownershipSection: string
  statusSection: string
  detailsSection: string
  /** Content-first anatomy (OD-REDESIGN-90 §2.3): the Relations region heading. */
  relatedSection: string
  statusField: string
  /** DO-13/I18N-2 — the record-door status pill + picker options localize the enum text
   *  (the pill's semantic hue stays keyed to the raw `value`, see record-field.tsx). */
  statusOpen: string
  statusInProgress: string
  statusBlocked: string
  statusDone: string
  descriptionField: string
  projectProcessField: string
  objectiveField: string
  sourceField: string
  /** Visible null-indicator for a read-only catalog field with no value (em dash). */
  noneMarker: string
  markComplete: string
  /** Lifecycle-aware primary action shown IN PLACE OF markComplete on an already-Done task
   *  (#751 AC-031: Reopen IS the header primary on a Done task, not a quiet secondary). */
  reopen: string
  /** Pinned-header meta-line prefixes (#751 AC-031, mockup "PIC <first name> · Supervisor
   *  <first name> · due Fri 28 Aug"). The owning-group item is unlabeled, so it needs no
   *  prefix key. */
  metaPic: string
  metaSupervisor: string
  metaDue: string
  unassigned: string
  archive: string
  unarchive: string
  readOnlyArchived: string
  readOnlyNoPermission: string
  /** E7 record grammar — conditional chip naming the generating process task definition;
   *  rendered only when the real `generated_from_task_def_id` provenance resolves a label. */
  generatedByField: string
}

const DEFAULT_TASK_RECORD_LABELS: TaskRecordLabels = {
  typeLabel: 'Task',
  ownershipSection: 'Task ownership',
  statusSection: 'Status & Timing',
  detailsSection: 'Task details',
  relatedSection: 'Related',
  statusField: 'Status',
  statusOpen: 'Open',
  statusInProgress: 'In Progress',
  statusBlocked: 'Blocked',
  statusDone: 'Done',
  descriptionField: 'Description',
  projectProcessField: 'Project/Process',
  objectiveField: 'Objective',
  sourceField: 'Source',
  noneMarker: '—',
  markComplete: 'Mark complete',
  reopen: 'Reopen',
  metaPic: 'PIC',
  metaSupervisor: 'Supervisor',
  metaDue: 'due',
  unassigned: 'Unassigned',
  archive: 'Archive task',
  unarchive: 'Unarchive',
  readOnlyArchived: 'This task is archived',
  // DO-23(b) (census R2 task-record P3-2): the note names the problem AND the recovery.
  readOnlyNoPermission: "You don't have permission to edit this task. Ask a manager or admin to change its ownership.",
  generatedByField: 'Generated by',
}

const DEFAULT_TASK_FIELD_LABELS: TaskFieldLabels = {
  businessUnit: 'Business Unit',
  pic: 'Person in charge (PIC)',
  supervisor: 'Supervisor',
  team: 'Team',
  teamUnassigned: TEAM_UNASSIGNED,
  teamFromRecord: 'Team is set from the task record',
  teamMigration: 'No team is assigned to this task yet (data migration).',
  dueDate: 'Due date',
  buPrefix: (name) => `BU: ${name}`,
  supervisorInherited: (name) => `inherited from ${name}`,
  createdBy: 'Created by',
  createdByLine: (name, date) => `Created by ${name} · ${date}`,
  adHoc: 'Ad hoc',
}

/** The honest Team field spec — Business Unit is NEVER relabelled Team; a real task.team_id lookup
 *  fills Team, otherwise it shows the honest migration state. This BUILDER is preserved as the
 *  Issue-8 seam (the internal model stays honest) but is NOT emitted into the rendered ownership
 *  fields until Issue 8's real team_id contract lands — record-collection plan §Task-11. Re-enabling
 *  the Team field is one call at the ownershipFields return site. */
export function teamOwnershipField(
  team: TaskTeamView | null | undefined,
  labels: TaskFieldLabels = DEFAULT_TASK_FIELD_LABELS,
): RecordFieldSpec {
  return {
    key: 'team',
    label: labels.team,
    control: 'team',
    value: team?.id ?? null,
    displayValue: team?.label ?? labels.teamUnassigned,
    editable: false,
    readOnlyReason: team ? labels.teamFromRecord : labels.teamMigration,
  }
}

/** The Task ownership fields — Team (with BU subline), PIC, Supervisor, Created by — shared by
 *  the full record adapter and any metadata-only panel adapter that follows the same anatomy.
 *
 *  #756 AC-036/037/039: Team is the owning EDITABLE field (picker scoped to the viewer's own
 *  teams and filtered to the task's BU — the DB's same-org + BU-equal guard is authoritative).
 *  Business Unit is NOT rendered as an editable field of its own — it appears ONLY as a "BU:
 *  <name>" subline beneath Team, because it is derived from the team, not chosen. Supervisor
 *  carries an "inherited from <first name>" subline when it mirrors the parent Project/Process
 *  Accountable (never when it doesn't). Created by is a read-only line at the foot of the
 *  section — a factual attribution, not a lifecycle event. */
function ownershipFields(input: {
  task: Pick<TaskListRow, 'business_unit_id' | 'responsible_person_id' | 'accountable_person_id'
    | 'created_by' | 'created_at' | 'team_id'>
  editable: boolean
  viewerId: string
  downlineIds: readonly string[]
  people: readonly PersonOption[]
  businessUnits: readonly BusinessUnitOption[]
  team: TaskTeamView | null | undefined
  viewerTeams: readonly ViewerTeamOption[]
  parentAccountablePersonId: string | null | undefined
  formatDate: (iso: string) => string
  labels: TaskFieldLabels
}): RecordFieldSpec[] {
  const {
    task, editable, viewerId, downlineIds, people, businessUnits, team, viewerTeams,
    parentAccountablePersonId, formatDate, labels,
  } = input

  // Team — editable ONLY when the writer has at least one eligible team AND the whole record is
  // editable; otherwise the honest read-only migration/no-team state (never a fabricated value).
  const teamCanEdit = editable && viewerTeams.length > 0
  const teamValue = task.team_id ?? team?.id ?? null
  const teamDisplay = teamValue
    ? (viewerTeams.find((t) => t.id === teamValue)?.label ?? team?.label ?? labels.teamUnassigned)
    : labels.teamUnassigned
  const teamBu = teamValue
    ? viewerTeams.find((t) => t.id === teamValue)?.businessUnitId
    : null
  // BU subline — resolved from the picked team when available (the derived fact), falling back
  // to the task's own BU column (the pre-#756 fossil that still tells the same story).
  const buForSubline = teamBu ?? task.business_unit_id
  const teamField: RecordFieldSpec = {
    key: 'team',
    label: labels.team,
    control: 'select',
    value: teamValue,
    displayValue: teamDisplay,
    options: viewerTeams.map((t) => ({ value: t.id, label: t.label })),
    editable: teamCanEdit,
    helperText: labels.buPrefix(buName(businessUnits, buForSubline, labels.teamUnassigned)),
    // When the record is editable but the writer has no eligible team, name why the picker is
    // absent — the "honest data-migration state" copy is exactly this seam (see teamOwnershipField).
    readOnlyReason: !teamCanEdit && editable ? labels.teamMigration : undefined,
  }

  const supervisorField: RecordFieldSpec = editableSpec(editable, {
    key: 'supervisor',
    label: labels.supervisor,
    control: 'person',
    value: task.accountable_person_id,
    displayValue: personName(people, task.accountable_person_id),
    options: personOptions(people),
    // AC-039: the "inherited from …" hint fires ONLY when this task's Supervisor equals the
    // parent Project/Process Accountable — every other case (no parent, parent has no A, or a
    // deliberate override) carries NO hint (silence is the honest neutral, not an em dash).
    helperText: parentAccountablePersonId && parentAccountablePersonId === task.accountable_person_id
      ? labels.supervisorInherited(firstName(personName(people, parentAccountablePersonId, labels.teamUnassigned)))
      : undefined,
  })

  // AC-037: "Created by <first name> · <date>", read-only. Rendered at the FOOT of the section
  // per the ticket's field order — a factual attribution, never a lifecycle button.
  const creatorName = personName(people, task.created_by, labels.teamUnassigned)
  const createdField: RecordFieldSpec = {
    key: 'createdBy',
    label: labels.createdBy,
    control: 'text',
    value: task.created_by,
    displayValue: labels.createdByLine(firstName(creatorName), formatDate(task.created_at)),
    editable: false,
    // The line itself is the derived fact — no permission reason, no BU subline.
  }

  return [
    teamField,
    editableSpec(editable, {
      key: 'pic',
      label: labels.pic,
      control: 'person',
      value: task.responsible_person_id,
      displayValue: personName(people, task.responsible_person_id),
      // Same contract as the inline picker (#742): the record's PIC picker offers the WRITER's
      // self + downline — the only values the DB's PIC-value clause accepts from this writer.
      options: personOptions(picOptions(viewerId, people, downlineIds)),
    }),
    supervisorField,
    createdField,
  ]
}

/** The Task due-date field (a text-like date control that holds a draft), shared by both adapters.
 *  `formatDate` renders the value-first DISPLAY string (item 2 — same formatter family as the table);
 *  `value` stays the raw ISO the edit control writes/reads. */
function dueField(
  task: Pick<TaskListRow, 'due_date'>,
  editable: boolean,
  label: string = DEFAULT_TASK_FIELD_LABELS.dueDate,
  formatDate: (iso: string) => string = (iso) => iso,
): RecordFieldSpec {
  return editableSpec(editable, {
    key: 'dueDate',
    label,
    control: 'date',
    value: task.due_date,
    displayValue: task.due_date ? formatDate(task.due_date) : 'No due date',
  })
}

/** Dispatch a domain-facing field commit to the correct DAL callback. Status is the
 *  one non-`updateTaskFields` field; every other key flows through onUpdateField. */
export function createTaskFieldCommit(
  input: Pick<TaskRecordAdapterInput, 'onUpdateField' | 'onUpdateStatus'>,
): (key: string, value: RecordValue) => Promise<void> {
  return async (key, value) => {
    if (key === 'status') {
      await input.onUpdateStatus(value as TaskStatus)
      return
    }
    await input.onUpdateField(key as TaskViewerFieldKey, value === null ? null : String(value))
  }
}

/** Locale-facing text for a status enum (DO-13/I18N-2) — the raw value stays the commit payload. */
function statusLabel(s: TaskStatus, L: TaskRecordLabels): string {
  return s === 'Open' ? L.statusOpen
    : s === 'In Progress' ? L.statusInProgress
    : s === 'Blocked' ? L.statusBlocked
    : L.statusDone
}

export function createTaskRecordAdapter(input: TaskRecordAdapterInput): RecordViewerAdapter {
  const {
    detail, viewerId, downlineIds, people, businessUnits, objectives = [], workLines = [], team,
    viewerTeams = [], parentAccountablePersonId, buildSourceHref,
  } = input
  const formatDate = input.formatDate ?? ((iso: string) => iso)
  const formatAge = input.formatAge
  const labels = { ...DEFAULT_TASK_FIELD_LABELS, ...(input.labels ?? {}) }
  const L = { ...DEFAULT_TASK_RECORD_LABELS, ...input.recordLabels }
  const task = detail.task
  const archived = task.archived_at !== null
  const editable = canEdit(task, viewerId, downlineIds) && !archived
  const canArchiveTask = canArchive(task, viewerId, downlineIds)

  // The ONE whole-record read-only note (why the viewer can't edit) — surfaced once by
  // RecordViewer's footer via `permission.reason` below. It is NOT stamped onto every field
  // (R4 — see editableSpec): a wall of identical per-field reasons was the noise the owner flagged.
  const readOnlyReason = archived ? L.readOnlyArchived : L.readOnlyNoPermission

  const editSpec = (spec: Omit<RecordFieldSpec, 'editable'>): RecordFieldSpec => ({
    ...spec,
    editable,
  })

  // Content-first document anatomy (OD-REDESIGN-90 §2.2, FR-ANAT-009): the Task leads with its
  // OWN content — Title (identity h1) + Description — then Ownership → Relations → Checklist →
  // Activity. The regions are packed into ORDERED content slots so the content leads without
  // flipping record-viewer.tsx's shared region order (which would endanger every other consumer
  // and paint the metadata region before content anyway). E7's calm-document intent is preserved;
  // only the ORDER obeys LAW-1 (content leads) / LAW-2 (Status + Due ride with the content).
  const workLine = workLines.find((row) => row.id === task.work_line_id) ?? null
  const workLineName = workLine?.name ?? null
  const objectiveName = objectives.find((row) => row.id === task.objective_id)?.name ?? null
  // R5 (owner review r2, owner-ratified DELETE): the derived Classification row was removed as a
  // fossil — it duplicated what the record already carries ("Generated" ⇒ the Generated-by chip,
  // "Project" ⇒ the Project/Process relation row, "Ad hoc" ⇒ the absence of both). It only existed
  // because the E7 mockup drew it (a quality floor, not a data spec), so no information is lost.
  const sourceDisplay = workLineName ?? objectiveName

  // 1. Content (LEADS) — Description prose directly beneath the identity title; Status pill + Due
  //    ride with it (LAW-2 — urgency adjacent to the content it qualifies, not a downstream block).
  const titleField = editSpec({
    key: 'title',
    label: 'title',
    control: 'text',
    value: task.title,
    displayValue: task.title,
  })
  const content: RecordMetadataSection = {
    id: 'content',
    label: L.detailsSection,
    fields: [
      editSpec({
        key: 'description',
        label: L.descriptionField,
        control: 'textarea',
        value: task.description,
        displayValue: task.description ?? L.noneMarker,
      }),
      editSpec({
        key: 'status',
        label: L.statusField,
        control: 'status',
        value: task.status,
        displayValue: statusLabel(task.status, L),
        options: TASK_STATUSES.map((s) => ({ value: s, label: statusLabel(s, L) })),
      }),
      dueField(task, editable, labels.dueDate, formatDate),
    ],
  }

  // 2. Ownership — Team (with "BU: <unit>" subline) · PIC · Supervisor (· inherited from <name>
  //    when it mirrors the parent Project/Process Accountable) · Created by <first name> · <date>.
  //    #756 AC-036: Team is the owning editable field; the editable Business Unit row is gone.
  //    The oracle's accessible name is "Task ownership".
  const ownership: RecordMetadataSection = {
    id: 'ownership',
    label: L.ownershipSection,
    fields: ownershipFields({
      task, editable, viewerId, downlineIds, people, businessUnits, team, viewerTeams,
      parentAccountablePersonId, formatDate, labels,
    }),
  }

  // 3. Relations — Project/Process · Objective (settable navigational links, "Ad hoc" when
  //    missing, AC-038 / DESIGN.md A7) · Generated-by · Source link chip (AC-042 — opens the
  //    parent in the panel stack; rendered only when a real attribution exists). The empty
  //    relation renders its DERIVED state word ("Ad hoc"), never the noneMarker em dash: an
  //    unattributed task is honestly ad hoc, not unattributable.
  const sourceHref = sourceDisplay
    ? (buildSourceHref?.({ workLineId: task.work_line_id, objectiveId: task.objective_id }) ?? null)
    : null
  const relations: RecordMetadataSection = {
    id: 'relations',
    label: L.relatedSection,
    fields: [
      editSpec({
        key: 'projectProcess',
        label: L.projectProcessField,
        control: 'relation',
        value: task.work_line_id,
        // AC-038: an unattributed Project/Process shows "Ad hoc" as its derived state word.
        // The option-list null entry keeps its em-dash so the picker still reads "no attribution"
        // in the drop-down (a picker's null option is a separate register from the value chip).
        displayValue: workLineName ?? labels.adHoc,
        options: [{ value: '', label: L.noneMarker }, ...workLines.map((row) => ({ value: row.id, label: row.name }))],
      }),
      editSpec({
        key: 'objective',
        label: L.objectiveField,
        control: 'relation',
        value: task.objective_id,
        displayValue: objectiveName ?? labels.adHoc,
        options: [{ value: '', label: L.noneMarker }, ...objectives.map((row) => ({ value: row.id, label: row.name }))],
      }),
      // Conditional (E7 record grammar) — rendered only when the real generating task
      // definition resolved a label; a hand-created (ad hoc) task carries no such chip.
      ...(input.generatedFromLabel
        ? [{
            key: 'generatedFrom',
            label: L.generatedByField,
            control: 'text' as const,
            value: input.generatedFromLabel,
            displayValue: input.generatedFromLabel,
            editable: false,
            readOnlyReason: undefined,
          }]
        : []),
      // Source — AC-042: a read-only chip that navigates to the parent (Project/Process or
      // Objective) in the panel stack. Rendered only when a real attribution EXISTS; a bare
      // ad-hoc task carries no Source row (the Project/Process and Objective rows above already
      // say "Ad hoc"). `linkHref` is the seam — the caller composes the concrete route via
      // buildSourceHref; without a href the chip degrades to plain text (never a dead link).
      ...(sourceDisplay
        ? [{
            key: 'source',
            label: L.sourceField,
            control: 'text' as const,
            value: task.work_line_id ?? task.objective_id ?? null,
            displayValue: sourceDisplay,
            editable: false,
            readOnlyReason: undefined,
            linkHref: sourceHref ?? undefined,
          }]
        : []),
    ],
  }

  // The pinned header's one-line summary (#751 AC-031, tasks-redesign-B): owning group · PIC ·
  // Supervisor · due · activity age. mos.tasks has no team_id yet (Issue 8), so the owning-group
  // slot shows the real team label when the lookup exists, otherwise the task's business unit —
  // the owning group the winning mockup draws ("Retail Ops"), never a fabricated team.
  const metaItems = [
    team?.label ?? buName(businessUnits, task.business_unit_id, L.noneMarker),
    `${L.metaPic} ${metaShortName(people, task.responsible_person_id, L.unassigned)}`,
    `${L.metaSupervisor} ${metaShortName(people, task.accountable_person_id, L.unassigned)}`,
    task.due_date ? `${L.metaDue} ${formatDate(task.due_date)}` : null,
    task.last_activity_at && formatAge ? formatAge(task.last_activity_at) : null,
  ].filter((item): item is string => item !== null)
  const headerMeta = metaItems.join(' · ')

  // Tab-strip counts (#751 AC-032): Checklist done/total, Activity = event count.
  const tabCounts = {
    checklist: { done: detail.checklist.filter((item) => item.is_done).length, total: detail.checklist.length },
    activity: detail.events.length,
  }

  const actions: RecordAction[] = []
  const allowedActionIds: string[] = []
  if (archived) {
    if (canArchiveTask) {
      actions.push({ id: 'unarchive', label: L.unarchive, intent: 'secondary', run: input.onUnarchive })
      allowedActionIds.push('unarchive')
    }
  } else {
    if (editable) {
      // Lifecycle-aware lead action (owner-eyes item 10): a Task whose status is already Done must
      // NOT offer a dead-end "Mark complete" primary. Reopening is a supported transition (the Status
      // control freely moves Done → any state), so a Done task instead offers a quiet "Reopen"
      // secondary that returns it to the active pool; every other state keeps "Mark complete".
      // onUpdateStatus RE-THROWS on failure (so the Status FIELD surfaces its visible error/retry).
      // A lifecycle-button trigger is fire-and-forget (`void action.run()` in RecordViewer), so the
      // button swallows the rejection here — the optimistic rollback + sr-only announce it already
      // performs is the button's feedback; without this catch a failed click is an unhandled rejection.
      if (task.status === 'Done') {
        actions.push({
          id: 'reopen',
          label: L.reopen,
          // #751 AC-031: the header has ONE primary slot; on a Done task Reopen IS it —
          // superseding owner-eyes item 10's quiet-secondary placement in the old footer bar.
          intent: 'primary',
          run: async () => { try { await input.onUpdateStatus('In Progress') } catch { /* surfaced via optimistic rollback */ } },
        })
        allowedActionIds.push('reopen')
      } else {
        actions.push({
          id: 'complete',
          label: L.markComplete,
          intent: 'primary',
          run: async () => { try { await input.onUpdateStatus('Done') } catch { /* surfaced via optimistic rollback */ } },
        })
        allowedActionIds.push('complete')
      }
    }
    if (canArchiveTask) {
      actions.push({ id: 'archive', label: L.archive, intent: 'secondary', run: input.onArchive })
      allowedActionIds.push('archive')
    }
  }

  // Each field section becomes an ordered CONTENT slot: its specs stay inspectable via `section`
  // and it renders through the shared RecordFieldList wired to the slot's field-commit seam — so a
  // relocated field keeps the exact value-first grammar, Escape isolation, and dirty-guard it had
  // in the metadata region. checklist + activity are the trailing content/audit regions; the live
  // TaskSurface overrides them with the interactive checklist + activity/comments composition.
  const contentSlots: RecordContentSlot[] = [
    fieldSectionSlot(content),
    fieldSectionSlot(ownership),
    fieldSectionSlot(relations),
    { id: 'checklist', label: 'Checklist', render: () => renderChecklist(detail) },
    { id: 'activity', label: 'Activity', render: () => renderActivity(detail) },
  ]

  return {
    kind: 'task',
    id: task.id,
    title: task.title,
    typeLabel: L.typeLabel,
    headerFields: [titleField, content.fields.find((field) => field.key === 'status')!],
    headerMeta,
    tabCounts,
    metadata: [],
    relations: [],
    contentSlots,
    activity: [],
    actions,
    permission: {
      readOnly: !editable,
      reason: editable ? undefined : readOnlyReason,
      allowedActionIds,
    },
    state: 'ready',
  }
}

/** Wrap a Task field section as an ordered content slot (content-first anatomy): the section
 *  specs are carried as DATA so the adapter stays inspectable, while `render` produces the same
 *  value-first RecordField markup the metadata region emits — wired through the slot's commit seam. */
function fieldSectionSlot(section: RecordMetadataSection): RecordContentSlot {
  return {
    id: section.id,
    label: section.label,
    section,
    render: (ctx) => (
      <RecordFieldList
        section={section}
        onCommitField={ctx.onCommitField}
        onDirtyChange={ctx.onDirtyChange}
        fieldCommitsFrozen={ctx.fieldCommitsFrozen}
        excludeKeys={section.id === 'content' ? ['status'] : []}
      />
    ),
  }
}

/** The default Activity (audit) region — the event log, last and quiet. The live TaskSurface
 *  overrides this slot with the interactive Activity + comment thread; this default keeps the
 *  adapter self-renderable (its own unit test) without a raw old→new diff dump (LAW-5 / F4). */
function renderActivity(detail: TaskDetail): ReactNode {
  if (detail.events.length === 0) {
    return <p className="record-activity__empty">No activity yet.</p>
  }
  return (
    <ul className="record-viewer__activity">
      {detail.events.map((e) => (
        <li key={e.id} className="record-viewer__activity-item">
          <span>{EVENT_LABELS[e.event_type] ?? e.event_type}</span>
          <time dateTime={e.created_at} className="record-viewer__activity-time">
            {e.created_at}
          </time>
        </li>
      ))}
    </ul>
  )
}

// Checklist is Task content that inherits the parent Task's PIC/Supervisor — it has NO
// independent ownership, status, Team, or due-date controls (plan Task 4).
function renderChecklist(detail: TaskDetail): ReactNode {
  if (detail.checklist.length === 0) {
    return <p className="record-checklist__empty">No checklist items.</p>
  }
  return (
    <ul className="record-checklist" aria-label="Checklist">
      {detail.checklist.map((item) => (
        <li key={item.id} className="record-checklist__item">
          <input type="checkbox" checked={item.is_done} disabled readOnly aria-label={item.label} />
          <span>{item.label}</span>
        </li>
      ))}
    </ul>
  )
}
