// createTaskRecordAdapter — projects the REAL Task model (mos.tasks / TaskDetail) into
// the shared RecordViewer grammar (V3 Issue 5, plan Task 4). A Task stays a Task: this
// adapter does not convert the row into a universal record, and it keeps every Task
// distinction the domain owns.
//
// Vocabulary is BINDING (CONTEXT.md): the legacy storage columns responsible_person_id /
// accountable_person_id are displayed as Person in charge (PIC) and Supervisor. The
// viewer NEVER exposes Responsible / Accountable / RACI / Consulted / Informed. Business
// Unit and Team are DISTINCT fields; while mos.tasks has no team_id the Team field is an
// honest "Team not assigned yet (data migration)" read-only state — never a BU relabel.
// The real Team-backed field/write path is the Issue 8 BU→Team re-home dependency.
//
// The one place the legacy person-storage mismatch is translated is the TaskSurface DAL
// switch (deferred host wiring); this adapter is entirely domain-facing.
import type { ReactNode } from 'react'
import type { TaskDetail } from '@/lib/db/tasks'
import type { TaskListRow, TaskStatus } from '@/lib/db/tasks.types'
import type { PersonOption, BusinessUnitOption } from '@/lib/db/directory'
import type { ObjectiveRow } from '@/lib/db/objectives'
import type { WorkLineRow } from '@/lib/db/work-lines'
import { canEdit, canArchive } from './task-permissions'
import type {
  RecordAction,
  RecordFieldOption,
  RecordFieldSpec,
  RecordMetadataSection,
  RecordActivityItem,
  RecordRelation,
  RecordValue,
  RecordViewerAdapter,
} from '@/components/records/record-viewer.types'

export type TaskViewerFieldKey =
  | 'title'
  | 'description'
  | 'dueDate'
  | 'businessUnit'
  | 'pic'
  | 'supervisor'
  | 'projectProcess'
  | 'objective'

export interface TaskTeamView {
  id: string
  label: string
}

export interface TaskRecordAdapterInput {
  detail: TaskDetail
  viewerId: string
  isManager: boolean
  people: readonly PersonOption[]
  businessUnits: readonly BusinessUnitOption[]
  objectives?: readonly ObjectiveRow[]
  workLines?: readonly WorkLineRow[]
  labels?: TaskFieldLabels
  /** Locale-resolved chrome labels for the full record (LocaleParityContract). */
  recordLabels?: Partial<TaskRecordLabels>
  /**
   * Only a real task.team_id lookup may populate this value. Omit or pass null while
   * the current mos.tasks row has no team_id (Issue 8 BU→Team re-home dependency).
   */
  team?: TaskTeamView | null
  /**
   * The generating `mos.process_task_defs.title` for a task materialized by
   * `mos.spawn_process_run` / `mos.resolve_pending_task` (ADR-0051 Step 6, real
   * `task.generated_from_task_def_id`). Omit or pass null for a hand-created (ad hoc)
   * task, or while the label lookup hasn't resolved yet — the "Generated by" chip is
   * conditional (E7 record grammar), never a fabricated placeholder.
   */
  generatedFromLabel?: string | null
  /**
   * Formats an ISO `YYYY-MM-DD` into the record's DISPLAY string. The live TaskSurface passes the
   * SAME `task-formatters.formatDate` family the table row uses (V3 owner-eyes item 2) so a record's
   * Due reads "Wed 8 Jul", never the raw ISO "2026-07-08". Omitted → the raw ISO is shown (keeps the
   * adapter's own unit tests literal). The field's `value` stays the ISO string for the edit control.
   */
  formatDate?: (iso: string) => string
  onUpdateField: (field: TaskViewerFieldKey, value: string | null) => Promise<void>
  onUpdateStatus: (next: TaskStatus) => Promise<void>
  onArchive: () => Promise<void>
  onUnarchive: () => Promise<void>
  onOpenRelated?: (relation: RecordRelation) => void
}

const TASK_STATUSES: readonly TaskStatus[] = ['Open', 'In Progress', 'Blocked', 'Done']
const TEAM_UNASSIGNED = 'Team not assigned yet (data migration)'

const EVENT_LABELS: Record<string, string> = {
  created: 'Created',
  status_changed: 'Status changed',
  field_edited: 'Field edited',
  raci_edited: 'Ownership edited',
  archived: 'Archived',
  unarchived: 'Unarchived',
}

function personOptions(people: readonly PersonOption[]): RecordFieldOption[] {
  return people.map((p) => ({ value: p.id, label: p.full_name }))
}
function personName(people: readonly PersonOption[], id: string | null): string {
  return people.find((p) => p.id === id)?.full_name ?? 'Unassigned'
}
function buOptions(bus: readonly BusinessUnitOption[]): RecordFieldOption[] {
  return bus.map((b) => ({ value: b.id, label: b.name }))
}
function buName(bus: readonly BusinessUnitOption[], id: string): string {
  return bus.find((b) => b.id === id)?.name ?? id
}

/** Wrap a field spec with the shared editable/read-only-reason policy. */
function editableSpec(
  editable: boolean,
  readOnlyReason: string,
  spec: Omit<RecordFieldSpec, 'editable'>,
): RecordFieldSpec {
  return { ...spec, editable, readOnlyReason: editable ? undefined : readOnlyReason }
}

/** i18n-able labels for the shared Task field builders. Defaults are English so the full
 *  createTaskRecordAdapter and the adapter's own unit tests keep their literals; the LIVE
 *  TaskSurface passes locale-resolved strings (LocaleParityContract). */
export interface TaskFieldLabels {
  businessUnit: string
  pic: string
  supervisor: string
  team: string
  teamUnassigned: string
  teamFromRecord: string
  teamMigration: string
  dueDate: string
}

/** i18n-able labels for the FULL Task record adapter's chrome — section titles, the
 *  catalog/provenance field labels, lifecycle actions, the type eyebrow, and the read-only
 *  reasons. Defaults are English so the adapter's own unit tests keep their literals; the
 *  LIVE TaskSurface passes locale-resolved strings (LocaleParityContract). The ownership
 *  landmark in particular must read "Task ownership" (the oracle's accessible name), NOT a
 *  bare "Ownership". */
export interface TaskRecordLabels {
  typeLabel: string
  ownershipSection: string
  statusSection: string
  detailsSection: string
  statusField: string
  descriptionField: string
  projectProcessField: string
  objectiveField: string
  sourceField: string
  sourceAdHoc: string
  /** Visible null-indicator for a read-only catalog field with no value (em dash). */
  noneMarker: string
  markComplete: string
  archive: string
  unarchive: string
  readOnlyArchived: string
  readOnlyNoPermission: string
  /** E7 record grammar — a derived, read-only provenance category (real data: process
   *  provenance beats a Project/Process attribution beats the honest Ad hoc default). */
  classificationField: string
  classificationGenerated: string
  classificationProject: string
  /** E7 record grammar — conditional chip naming the generating process task definition;
   *  rendered only when the real `generated_from_task_def_id` provenance resolves a label. */
  generatedByField: string
}

const DEFAULT_TASK_RECORD_LABELS: TaskRecordLabels = {
  typeLabel: 'Task',
  ownershipSection: 'Task ownership',
  statusSection: 'Status & Timing',
  detailsSection: 'Task details',
  statusField: 'Status',
  descriptionField: 'Description',
  projectProcessField: 'Project/Process',
  objectiveField: 'Objective',
  sourceField: 'Source',
  sourceAdHoc: 'Ad hoc',
  noneMarker: '—',
  markComplete: 'Mark complete',
  archive: 'Archive task',
  unarchive: 'Unarchive',
  readOnlyArchived: 'This task is archived',
  readOnlyNoPermission: "You don't have permission to edit this task.",
  classificationField: 'Classification',
  classificationGenerated: 'Generated',
  classificationProject: 'Project',
  generatedByField: 'Generated by',
}

const DEFAULT_TASK_FIELD_LABELS: TaskFieldLabels = {
  businessUnit: 'Business Unit',
  pic: 'Person in charge (PIC)',
  supervisor: 'Supervisor',
  team: 'Team',
  teamUnassigned: TEAM_UNASSIGNED,
  teamFromRecord: 'Team is set from the task record',
  teamMigration: 'No team is assigned to this task yet (data migration).',
  dueDate: 'Due date',
}

/** The honest Team field spec — Business Unit is NEVER relabelled Team; a real task.team_id lookup
 *  fills Team, otherwise it shows the honest migration state. This BUILDER is preserved as the
 *  Issue-8 seam (the internal model stays honest) but is NOT emitted into the rendered ownership
 *  fields until Issue 8's real team_id contract lands — record-collection plan §Task-11. Re-enabling
 *  the Team field is one call at the ownershipFields return site. */
export function teamOwnershipField(
  team: TaskTeamView | null | undefined,
  labels: TaskFieldLabels = DEFAULT_TASK_FIELD_LABELS,
): RecordFieldSpec {
  return {
    key: 'team',
    label: labels.team,
    control: 'team',
    value: team?.id ?? null,
    displayValue: team?.label ?? labels.teamUnassigned,
    editable: false,
    readOnlyReason: team ? labels.teamFromRecord : labels.teamMigration,
  }
}

/** The Task ownership fields — Business Unit, PIC, Supervisor — shared by the full record adapter
 *  and the metadata-only panel adapter.
 *
 *  §Task-11 (Issue-8 gate): the Team field is NOT rendered here until Issue 8 supplies the real
 *  mos.tasks.team_id contract. The `team` input is still ACCEPTED so the adapter's internal model
 *  stays honest (see teamOwnershipField above), but no Team field is projected into the record UI. */
function ownershipFields(
  task: Pick<TaskListRow, 'business_unit_id' | 'responsible_person_id' | 'accountable_person_id'>,
  editable: boolean,
  readOnlyReason: string,
  people: readonly PersonOption[],
  businessUnits: readonly BusinessUnitOption[],
  // `_team` is accepted (callers still supply it, so the internal model stays honest — the Issue-8
  // seam via teamOwnershipField) but intentionally NOT rendered until Issue 8's real team_id
  // contract lands (record-collection plan §Task-11).
  _team: TaskTeamView | null | undefined,
  labels: TaskFieldLabels = DEFAULT_TASK_FIELD_LABELS,
): RecordFieldSpec[] {
  return [
    editableSpec(editable, readOnlyReason, {
      key: 'businessUnit',
      label: labels.businessUnit,
      control: 'select',
      value: task.business_unit_id,
      displayValue: buName(businessUnits, task.business_unit_id),
      options: buOptions(businessUnits),
    }),
    editableSpec(editable, readOnlyReason, {
      key: 'pic',
      label: labels.pic,
      control: 'person',
      value: task.responsible_person_id,
      displayValue: personName(people, task.responsible_person_id),
      options: personOptions(people),
    }),
    editableSpec(editable, readOnlyReason, {
      key: 'supervisor',
      label: labels.supervisor,
      control: 'person',
      value: task.accountable_person_id,
      displayValue: personName(people, task.accountable_person_id),
      options: personOptions(people),
    }),
  ]
}

/** The Task due-date field (a text-like date control that holds a draft), shared by both adapters.
 *  `formatDate` renders the value-first DISPLAY string (item 2 — same formatter family as the table);
 *  `value` stays the raw ISO the edit control writes/reads. */
function dueField(
  task: Pick<TaskListRow, 'due_date'>,
  editable: boolean,
  readOnlyReason: string,
  label: string = DEFAULT_TASK_FIELD_LABELS.dueDate,
  formatDate: (iso: string) => string = (iso) => iso,
): RecordFieldSpec {
  return editableSpec(editable, readOnlyReason, {
    key: 'dueDate',
    label,
    control: 'date',
    value: task.due_date,
    displayValue: task.due_date ? formatDate(task.due_date) : 'No due date',
  })
}

/** The Classification chip (E7 record grammar) — a derived, read-only provenance category,
 *  never a stored/editable field. Real-data precedence: an occurrence-materialized task
 *  (`process_run_id` or `generated_from_task_def_id` stamped by `mos.spawn_process_run` /
 *  `mos.resolve_pending_task`, ADR-0051 Step 6) is "Generated"; a task attributed to a
 *  Project-type work line is "Project"; everything else is the honest "Ad hoc" default —
 *  the same default the Source field already uses. */
function taskClassification(
  task: Pick<TaskListRow, 'process_run_id' | 'generated_from_task_def_id'>,
  workLineType: WorkLineRow['type'] | null,
  L: TaskRecordLabels,
): string {
  if (task.process_run_id || task.generated_from_task_def_id) return L.classificationGenerated
  if (workLineType === 'project') return L.classificationProject
  return L.sourceAdHoc
}

/** Dispatch a domain-facing field commit to the correct DAL callback. Status is the
 *  one non-`updateTaskFields` field; every other key flows through onUpdateField. */
export function createTaskFieldCommit(
  input: Pick<TaskRecordAdapterInput, 'onUpdateField' | 'onUpdateStatus'>,
): (key: string, value: RecordValue) => Promise<void> {
  return async (key, value) => {
    if (key === 'status') {
      await input.onUpdateStatus(value as TaskStatus)
      return
    }
    await input.onUpdateField(key as TaskViewerFieldKey, value === null ? null : String(value))
  }
}

export function createTaskRecordAdapter(input: TaskRecordAdapterInput): RecordViewerAdapter {
  const { detail, viewerId, isManager, people, businessUnits, objectives = [], workLines = [], team } = input
  const formatDate = input.formatDate ?? ((iso: string) => iso)
  const labels = input.labels ?? DEFAULT_TASK_FIELD_LABELS
  const L = { ...DEFAULT_TASK_RECORD_LABELS, ...input.recordLabels }
  const task = detail.task
  const archived = task.archived_at !== null
  const editable = canEdit(task, viewerId, isManager) && !archived
  const canArchiveTask = canArchive(task, viewerId, isManager)

  const readOnlyReason = archived ? L.readOnlyArchived : L.readOnlyNoPermission

  const editSpec = (spec: Omit<RecordFieldSpec, 'editable'>): RecordFieldSpec => ({
    ...spec,
    editable,
    readOnlyReason: editable ? undefined : readOnlyReason,
  })

  // Document anatomy (E7 record): Ownership → Status & Timing → Details → Activity. A Task
  // reads as a calm document, not a settings form — each field renders its value first
  // (RecordField value-first grammar) and swaps in its control on activation.
  const workLine = workLines.find((row) => row.id === task.work_line_id) ?? null
  const workLineName = workLine?.name ?? null
  const objectiveName = objectives.find((row) => row.id === task.objective_id)?.name ?? null
  const classification = taskClassification(task, workLine?.type ?? null, L)
  const sourceDisplay = workLineName ?? objectiveName ?? L.sourceAdHoc

  // Ownership landmark — Business Unit · PIC · Supervisor · Classification · Source. Classification
  // and Source are both read-only DERIVED provenance (never editable; they mirror the real
  // process/work-line/objective attribution, never a stored column). Team stays gated off until
  // Issue 8's real team_id contract (§Task-11). The oracle's accessible name is "Task ownership".
  const ownership: RecordMetadataSection = {
    id: 'ownership',
    label: L.ownershipSection,
    fields: [
      ...ownershipFields(task, editable, readOnlyReason, people, businessUnits, team, labels),
      {
        key: 'classification',
        label: L.classificationField,
        control: 'text',
        value: classification,
        displayValue: classification,
        editable: false,
        readOnlyReason: undefined,
      },
      // Source/provenance — read-only derived summary (never editable; it mirrors the selects).
      // Collapsed when it would repeat Classification's value verbatim (F4: a hand-created task
      // showed "Classification: Ad hoc" AND "Source: Ad hoc" — the same value twice, thin next
      // to E7's populated provenance). Kept whenever it carries real information Classification
      // doesn't (e.g. Classification "Ad hoc" + Source "Today opening", or Classification
      // "Project" + Source "New menu launch").
      ...(sourceDisplay !== classification
        ? [{
            key: 'source',
            label: L.sourceField,
            control: 'text' as const,
            value: task.work_line_id ?? task.objective_id ?? null,
            displayValue: sourceDisplay,
            editable: false,
            readOnlyReason: undefined,
          }]
        : []),
    ],
  }

  // Status & Timing — the lifecycle pill + Due, then the provenance/attribution relations we
  // actually hold (Project/Process, Objective) woven in as relation chips WHERE the data exists.
  const statusSection: RecordMetadataSection = {
    id: 'status',
    label: L.statusSection,
    fields: [
      editSpec({
        key: 'status',
        label: L.statusField,
        control: 'status',
        value: task.status,
        displayValue: task.status,
        options: TASK_STATUSES.map((s) => ({ value: s, label: s })),
      }),
      dueField(task, editable, readOnlyReason, labels.dueDate, formatDate),
      editSpec({
        key: 'projectProcess',
        label: L.projectProcessField,
        control: 'relation',
        value: task.work_line_id,
        displayValue: workLineName ?? L.noneMarker,
        options: [{ value: '', label: L.noneMarker }, ...workLines.map((row) => ({ value: row.id, label: row.name }))],
      }),
      editSpec({
        key: 'objective',
        label: L.objectiveField,
        control: 'relation',
        value: task.objective_id,
        displayValue: objectiveName ?? L.noneMarker,
        options: [{ value: '', label: L.noneMarker }, ...objectives.map((row) => ({ value: row.id, label: row.name }))],
      }),
      // Conditional (E7 record grammar) — rendered only when the real generating task
      // definition resolved a label; a hand-created (ad hoc) task carries no such chip.
      ...(input.generatedFromLabel
        ? [{
            key: 'generatedFrom',
            label: L.generatedByField,
            control: 'text' as const,
            value: input.generatedFromLabel,
            displayValue: input.generatedFromLabel,
            editable: false,
            readOnlyReason: undefined,
          }]
        : []),
    ],
  }

  // Details — description as prose (prose-first). Title is NOT re-listed: the RecordViewer
  // identity header already owns the record-name heading (no-duplicate-h1 / ViewerIdentity-
  // Suppression contract), so a Title field would render the same name twice.
  const details: RecordMetadataSection = {
    id: 'details',
    label: L.detailsSection,
    fields: [
      editSpec({
        key: 'description',
        label: L.descriptionField,
        control: 'textarea',
        value: task.description,
        displayValue: task.description ?? L.noneMarker,
      }),
    ],
  }

  const activity: RecordActivityItem[] = detail.events.map((e) => ({
    id: e.id,
    label: EVENT_LABELS[e.event_type] ?? e.event_type,
    occurredAt: e.created_at,
  }))

  const actions: RecordAction[] = []
  const allowedActionIds: string[] = []
  if (archived) {
    if (canArchiveTask) {
      actions.push({ id: 'unarchive', label: L.unarchive, intent: 'secondary', run: input.onUnarchive })
      allowedActionIds.push('unarchive')
    }
  } else {
    if (editable) {
      actions.push({
        id: 'complete',
        label: L.markComplete,
        intent: 'primary',
        run: () => input.onUpdateStatus('Done'),
      })
      allowedActionIds.push('complete')
    }
    if (canArchiveTask) {
      actions.push({ id: 'archive', label: L.archive, intent: 'secondary', run: input.onArchive })
      allowedActionIds.push('archive')
    }
  }

  return {
    kind: 'task',
    id: task.id,
    title: task.title,
    typeLabel: L.typeLabel,
    metadata: [ownership, statusSection, details],
    relations: [],
    contentSlots: [
      {
        id: 'checklist',
        label: 'Checklist',
        render: () => renderChecklist(detail),
      },
    ],
    activity,
    actions,
    permission: {
      readOnly: !editable,
      reason: editable ? undefined : readOnlyReason,
      allowedActionIds,
    },
    state: 'ready',
  }
}

// Checklist is Task content that inherits the parent Task's PIC/Supervisor — it has NO
// independent ownership, status, Team, or due-date controls (plan Task 4).
function renderChecklist(detail: TaskDetail): ReactNode {
  if (detail.checklist.length === 0) {
    return <p className="record-checklist__empty">No checklist items.</p>
  }
  return (
    <ul className="record-checklist" aria-label="Checklist">
      {detail.checklist.map((item) => (
        <li key={item.id} className="record-checklist__item">
          <input type="checkbox" checked={item.is_done} disabled readOnly aria-label={item.label} />
          <span>{item.label}</span>
        </li>
      ))}
    </ul>
  )
}
