// Generated by scripts/mcp-catalog.sh from the api_v1 function comments. Do not edit; change the
// COMMENT in the migration and regenerate. One entry per api_v1 operation: the MCP server offers
// exactly these as tools.
import type { ApiV1Operation } from './types.ts'

export const API_V1_CATALOG: readonly ApiV1Operation[] = [
  {
    "name": "add_checklist_item",
    "purpose": "add a checklist item to a Task (at most 100 items).",
    "inputs": "task_id, label (at most 300 characters), position (default: the end).",
    "returns": "{item} (the Task as get_task returns it).",
    "errors": "invalid_input, not_found (task_id), forbidden, rate_limited.",
    "args": [
      {
        "name": "task_id",
        "type": "uuid",
        "required": true
      },
      {
        "name": "label",
        "type": "text",
        "required": true
      },
      {
        "name": "position",
        "type": "integer",
        "required": false
      }
    ]
  },
  {
    "name": "create_project_process",
    "purpose": "create a Project or Process.",
    "inputs": "name (at most 200 characters), type (project or process), business_unit_id, objective_id, accountable_person_id, responsible_person_id, idempotency_key (1 to 200 characters; the same person repeating it within 24 hours gets the same record back with replayed true).",
    "returns": "{item, replayed}.",
    "errors": "invalid_input, not_found (business_unit_id), forbidden (only a person who manages that unit's definitions), rate_limited (60 writes a minute per person).",
    "args": [
      {
        "name": "name",
        "type": "text",
        "required": true
      },
      {
        "name": "type",
        "type": "text",
        "required": true
      },
      {
        "name": "business_unit_id",
        "type": "uuid",
        "required": false
      },
      {
        "name": "objective_id",
        "type": "uuid",
        "required": false
      },
      {
        "name": "accountable_person_id",
        "type": "uuid",
        "required": false
      },
      {
        "name": "responsible_person_id",
        "type": "uuid",
        "required": false
      },
      {
        "name": "idempotency_key",
        "type": "text",
        "required": false
      }
    ]
  },
  {
    "name": "create_signal",
    "purpose": "post an org-wide Signal as the caller through the app's posting function, so mention rules, the recipient cap and notifications are unchanged.",
    "inputs": "body (at most 4000 characters), occurred_at (default now), attention (FYI, Needs attention or Urgent; default FYI), mentions (at most 50 of {kind person, team or business_unit; id}), link_task_ids (at most 10 Tasks to link), idempotency_key (1 to 200 characters; the same person repeating it within 24 hours gets the same Signal back with replayed true).",
    "returns": "{item, replayed}.",
    "errors": "invalid_input, not_found (link_task_ids), forbidden (posting or mention rules), rate_limited (60 writes a minute per person).",
    "args": [
      {
        "name": "body",
        "type": "text",
        "required": true
      },
      {
        "name": "occurred_at",
        "type": "timestamp with time zone",
        "required": false
      },
      {
        "name": "attention",
        "type": "text",
        "required": false
      },
      {
        "name": "mentions",
        "type": "jsonb",
        "required": false
      },
      {
        "name": "link_task_ids",
        "type": "uuid[]",
        "required": false
      },
      {
        "name": "idempotency_key",
        "type": "text",
        "required": false
      }
    ]
  },
  {
    "name": "create_task",
    "purpose": "create a Task; the Business Unit comes from the Team and the created event is written with it.",
    "inputs": "title (at most 300 characters), team_id, responsible_person_id, accountable_person_id, description (at most 2000), due_date, status (default Open), consulted_person_ids and informed_person_ids (at most 50 each), objective_id, work_line_id, checklist (at most 50 labels of at most 300 characters), idempotency_key (1 to 200 characters; the same person repeating it within 24 hours gets the same Task back with replayed true).",
    "returns": "{item, replayed}.",
    "errors": "invalid_input, not_found (team_id), forbidden (a rule such as who may be person in charge), rate_limited (60 writes a minute per person).",
    "args": [
      {
        "name": "title",
        "type": "text",
        "required": true
      },
      {
        "name": "team_id",
        "type": "uuid",
        "required": true
      },
      {
        "name": "responsible_person_id",
        "type": "uuid",
        "required": true
      },
      {
        "name": "accountable_person_id",
        "type": "uuid",
        "required": true
      },
      {
        "name": "description",
        "type": "text",
        "required": false
      },
      {
        "name": "due_date",
        "type": "date",
        "required": false
      },
      {
        "name": "status",
        "type": "text",
        "required": false
      },
      {
        "name": "consulted_person_ids",
        "type": "uuid[]",
        "required": false
      },
      {
        "name": "informed_person_ids",
        "type": "uuid[]",
        "required": false
      },
      {
        "name": "objective_id",
        "type": "uuid",
        "required": false
      },
      {
        "name": "work_line_id",
        "type": "uuid",
        "required": false
      },
      {
        "name": "checklist",
        "type": "text[]",
        "required": false
      },
      {
        "name": "idempotency_key",
        "type": "text",
        "required": false
      }
    ]
  },
  {
    "name": "edit_objective_write_up",
    "purpose": "replace an Objective's write-up; allowed for an ops lead, an admin, and the head of the Objective's own Business Unit.",
    "inputs": "id; write_up (a list of at most 256 KB of blocks, each an object with a text type; use an empty list to clear); expected_updated_at (required; the updated_at you read, a newer one is a conflict).",
    "returns": "{item} (the Objective as get_objective returns it).",
    "errors": "invalid_input (write_up, expected_updated_at), not_found, forbidden, conflict, rate_limited. This operation has no input for an Objective's name, unit, period, owner or key-result targets and never returns refused.targets; only refused_action answers such a request with refused.targets.",
    "args": [
      {
        "name": "id",
        "type": "uuid",
        "required": true
      },
      {
        "name": "write_up",
        "type": "jsonb",
        "required": true
      },
      {
        "name": "expected_updated_at",
        "type": "timestamp with time zone",
        "required": true
      }
    ]
  },
  {
    "name": "edit_project_process",
    "purpose": "change a Project or Process.",
    "inputs": "id; changes, an object holding any of name, objective_id, business_unit_id, accountable_person_id, responsible_person_id (type and the internal code are never accepted: invalid_input); expected_updated_at (the updated_at you read; a newer one is a conflict). Archive keys are refused.",
    "returns": "{item}.",
    "errors": "invalid_input, refused.archive, not_found, forbidden, conflict, rate_limited.",
    "args": [
      {
        "name": "id",
        "type": "uuid",
        "required": true
      },
      {
        "name": "changes",
        "type": "jsonb",
        "required": true
      },
      {
        "name": "expected_updated_at",
        "type": "timestamp with time zone",
        "required": false
      }
    ]
  },
  {
    "name": "edit_signal",
    "purpose": "change a Signal's content; only its author may.",
    "inputs": "id; changes, an object holding any of body, occurred_at, category (or null), attention; expected_updated_at (the updated_at you read; a newer one is a conflict). The guard records each changed field as a revision. Audience, owning-team and mention keys are refused.permissions; retraction and archive keys are refused.archive.",
    "returns": "{item} (the Signal as get_signal returns it).",
    "errors": "invalid_input (unknown key or bad value), refused.permissions, refused.archive, not_found, forbidden, conflict, rate_limited.",
    "args": [
      {
        "name": "id",
        "type": "uuid",
        "required": true
      },
      {
        "name": "changes",
        "type": "jsonb",
        "required": true
      },
      {
        "name": "expected_updated_at",
        "type": "timestamp with time zone",
        "required": false
      }
    ]
  },
  {
    "name": "edit_task",
    "purpose": "change a Task.",
    "inputs": "id; changes, an object holding any of title, description, due_date, status, team_id (the Business Unit follows), responsible_person_id, accountable_person_id, consulted_person_ids, informed_person_ids, objective_id, work_line_id; expected_updated_at (the updated_at you read; a newer one is a conflict). The same task events the app writes are recorded. Archive keys are refused.",
    "returns": "{item}.",
    "errors": "invalid_input (unknown key or bad value), refused.archive, not_found, forbidden, conflict, rate_limited.",
    "args": [
      {
        "name": "id",
        "type": "uuid",
        "required": true
      },
      {
        "name": "changes",
        "type": "jsonb",
        "required": true
      },
      {
        "name": "expected_updated_at",
        "type": "timestamp with time zone",
        "required": false
      }
    ]
  },
  {
    "name": "get_objective",
    "purpose": "one Objective with its key results and its write-up (a list of blocks, or null).",
    "inputs": "id.",
    "returns": "{item} (the list_objectives shape plus write_up).",
    "errors": "not_found, invalid_input (id).",
    "args": [
      {
        "name": "id",
        "type": "uuid",
        "required": true
      }
    ]
  },
  {
    "name": "get_project_process",
    "purpose": "one Project or Process.",
    "inputs": "id.",
    "returns": "{item}.",
    "errors": "not_found, invalid_input (id).",
    "args": [
      {
        "name": "id",
        "type": "uuid",
        "required": true
      }
    ]
  },
  {
    "name": "get_record_history",
    "purpose": "the change history of one record, newest first, read through the same visibility rule as the app.",
    "inputs": "record_type (task, signal, project_process or objective), id, cursor (opaque, from next_cursor), limit (default 50, at most 100).",
    "returns": "{items [{id, action (insert, update or delete), field, old_value, new_value, actor_person_id, actor_name, channel (app, api or agent), agent_client_id, occurred_at}], next_cursor}. A record type whose history is not yet recorded, or a record the caller cannot read, returns no items.",
    "errors": "invalid_input (record_type, id, cursor, limit).",
    "args": [
      {
        "name": "record_type",
        "type": "text",
        "required": true
      },
      {
        "name": "id",
        "type": "uuid",
        "required": true
      },
      {
        "name": "cursor",
        "type": "text",
        "required": false
      },
      {
        "name": "limit",
        "type": "integer",
        "required": false
      }
    ]
  },
  {
    "name": "get_signal",
    "purpose": "one Signal with its active mentions [{kind person, team or business_unit; id}], latest 50 comments, acknowledged_by_me and linked Task ids.",
    "inputs": "id.",
    "returns": "{item}.",
    "errors": "not_found (missing or not readable), invalid_input (id).",
    "args": [
      {
        "name": "id",
        "type": "uuid",
        "required": true
      }
    ]
  },
  {
    "name": "get_task",
    "purpose": "one Task with its checklist (at most 100), latest 50 events, latest 50 comments and all linked Signal ids.",
    "inputs": "id.",
    "returns": "{item}.",
    "errors": "not_found (missing or not readable), invalid_input (id).",
    "args": [
      {
        "name": "id",
        "type": "uuid",
        "required": true
      }
    ]
  },
  {
    "name": "link_signal_task",
    "purpose": "link a Signal to a Task; an existing link is success.",
    "inputs": "signal_id, task_id.",
    "returns": "{item} (the Signal as get_signal returns it).",
    "errors": "invalid_input, not_found (signal_id or task_id), forbidden, rate_limited.",
    "args": [
      {
        "name": "signal_id",
        "type": "uuid",
        "required": true
      },
      {
        "name": "task_id",
        "type": "uuid",
        "required": true
      }
    ]
  },
  {
    "name": "list_business_units",
    "purpose": "live Business Units in the caller's org.",
    "inputs": "none.",
    "returns": "{items [{id, name, code}] (at most 100), next_cursor: null}.",
    "errors": "none expected.",
    "args": []
  },
  {
    "name": "list_objectives",
    "purpose": "Objectives in the caller's org, newest period first (the whole year before its quarters, then by name).",
    "inputs": "business_unit_id, company_wide (true for Company-wide Objectives only, false to exclude them), period_year, period_quarter (1 to 4), q (name contains, at most 200 characters), include_archived (default false), cursor, limit (default 50, at most 100).",
    "returns": "{items [Objective: id, name, business_unit_id, is_company_wide, period_year, period_quarter, accountable_person_id, progress {done, total} or null, key_results [{id, what, target_value, current_value, unit, due_date, owner_person_id, updated_at}], archived_at, created_at, updated_at], next_cursor}.",
    "errors": "invalid_input (period_quarter, q, cursor, limit).",
    "args": [
      {
        "name": "business_unit_id",
        "type": "uuid",
        "required": false
      },
      {
        "name": "company_wide",
        "type": "boolean",
        "required": false
      },
      {
        "name": "period_year",
        "type": "integer",
        "required": false
      },
      {
        "name": "period_quarter",
        "type": "integer",
        "required": false
      },
      {
        "name": "q",
        "type": "text",
        "required": false
      },
      {
        "name": "include_archived",
        "type": "boolean",
        "required": false
      },
      {
        "name": "cursor",
        "type": "text",
        "required": false
      },
      {
        "name": "limit",
        "type": "integer",
        "required": false
      }
    ]
  },
  {
    "name": "list_people",
    "purpose": "people in the caller's org.",
    "inputs": "q (name or email contains), team_id (live members of that Team), include_archived (default false), cursor (opaque, from next_cursor), limit (default 50, at most 100).",
    "returns": "{items [{id, full_name, email, teams [{team_id, name}]}], next_cursor}.",
    "errors": "invalid_input (q over 200 characters, cursor, limit).",
    "args": [
      {
        "name": "q",
        "type": "text",
        "required": false
      },
      {
        "name": "team_id",
        "type": "uuid",
        "required": false
      },
      {
        "name": "include_archived",
        "type": "boolean",
        "required": false
      },
      {
        "name": "cursor",
        "type": "text",
        "required": false
      },
      {
        "name": "limit",
        "type": "integer",
        "required": false
      }
    ]
  },
  {
    "name": "list_projects_processes",
    "purpose": "Projects and Processes in the caller's org by name.",
    "inputs": "type (project or process), objective_id, business_unit_id, updated_since, q (name contains, at most 200 characters), include_archived (default false), cursor, limit (default 50, at most 100).",
    "returns": "{items [Project/Process], next_cursor}.",
    "errors": "invalid_input (type, q, cursor, limit).",
    "args": [
      {
        "name": "type",
        "type": "text",
        "required": false
      },
      {
        "name": "objective_id",
        "type": "uuid",
        "required": false
      },
      {
        "name": "business_unit_id",
        "type": "uuid",
        "required": false
      },
      {
        "name": "updated_since",
        "type": "timestamp with time zone",
        "required": false
      },
      {
        "name": "q",
        "type": "text",
        "required": false
      },
      {
        "name": "include_archived",
        "type": "boolean",
        "required": false
      },
      {
        "name": "cursor",
        "type": "text",
        "required": false
      },
      {
        "name": "limit",
        "type": "integer",
        "required": false
      }
    ]
  },
  {
    "name": "list_signals",
    "purpose": "Signals the caller can read, newest occurred_at first.",
    "inputs": "attention (at most 50 of FYI, Needs attention, Urgent), author_id (a filter, never an actor), occurred_from, occurred_to, linked_task_id, updated_since, q (body contains, at most 200 characters), include_retracted (default false), cursor, limit (default 50, at most 100).",
    "returns": "{items [Signal], next_cursor}.",
    "errors": "invalid_input (attention, q, cursor, limit).",
    "args": [
      {
        "name": "attention",
        "type": "text[]",
        "required": false
      },
      {
        "name": "author_id",
        "type": "uuid",
        "required": false
      },
      {
        "name": "occurred_from",
        "type": "timestamp with time zone",
        "required": false
      },
      {
        "name": "occurred_to",
        "type": "timestamp with time zone",
        "required": false
      },
      {
        "name": "linked_task_id",
        "type": "uuid",
        "required": false
      },
      {
        "name": "updated_since",
        "type": "timestamp with time zone",
        "required": false
      },
      {
        "name": "q",
        "type": "text",
        "required": false
      },
      {
        "name": "include_retracted",
        "type": "boolean",
        "required": false
      },
      {
        "name": "cursor",
        "type": "text",
        "required": false
      },
      {
        "name": "limit",
        "type": "integer",
        "required": false
      }
    ]
  },
  {
    "name": "list_tasks",
    "purpose": "Tasks the caller can read, newest updated_at first.",
    "inputs": "status (list of Open, In Progress, Blocked, Done), team_id, business_unit_id, responsible_person_id, accountable_person_id, objective_id, work_line_id, due_from, due_to, updated_since, q (title contains), include_archived (default false), cursor, limit (default 50, at most 100).",
    "returns": "{items [Task], next_cursor}.",
    "errors": "invalid_input (q over 200 characters, status, cursor, limit).",
    "args": [
      {
        "name": "status",
        "type": "text[]",
        "required": false
      },
      {
        "name": "team_id",
        "type": "uuid",
        "required": false
      },
      {
        "name": "business_unit_id",
        "type": "uuid",
        "required": false
      },
      {
        "name": "responsible_person_id",
        "type": "uuid",
        "required": false
      },
      {
        "name": "accountable_person_id",
        "type": "uuid",
        "required": false
      },
      {
        "name": "objective_id",
        "type": "uuid",
        "required": false
      },
      {
        "name": "work_line_id",
        "type": "uuid",
        "required": false
      },
      {
        "name": "due_from",
        "type": "date",
        "required": false
      },
      {
        "name": "due_to",
        "type": "date",
        "required": false
      },
      {
        "name": "updated_since",
        "type": "timestamp with time zone",
        "required": false
      },
      {
        "name": "q",
        "type": "text",
        "required": false
      },
      {
        "name": "include_archived",
        "type": "boolean",
        "required": false
      },
      {
        "name": "cursor",
        "type": "text",
        "required": false
      },
      {
        "name": "limit",
        "type": "integer",
        "required": false
      }
    ]
  },
  {
    "name": "list_teams",
    "purpose": "live Teams in the caller's org.",
    "inputs": "q (name or code contains), business_unit_id, cursor, limit (default 50, at most 100).",
    "returns": "{items [{id, name, code, business_unit_id, business_unit_name, site_id}], next_cursor}.",
    "errors": "invalid_input (q over 200 characters, cursor, limit).",
    "args": [
      {
        "name": "q",
        "type": "text",
        "required": false
      },
      {
        "name": "business_unit_id",
        "type": "uuid",
        "required": false
      },
      {
        "name": "cursor",
        "type": "text",
        "required": false
      },
      {
        "name": "limit",
        "type": "integer",
        "required": false
      }
    ]
  },
  {
    "name": "refused_action",
    "purpose": "answers a risky request with the fixed \"do this in MOS\" refusal.",
    "inputs": "action (archive, restore, retract, delete, change_objective, change_target, change_permissions, money); record_type and id are accepted and never read.",
    "errors": "Always raises: refused.archive, refused.delete, refused.targets, refused.permissions or refused.money; invalid_input for an unknown action.",
    "args": [
      {
        "name": "action",
        "type": "text",
        "required": true
      },
      {
        "name": "record_type",
        "type": "text",
        "required": false
      },
      {
        "name": "id",
        "type": "uuid",
        "required": false
      }
    ]
  },
  {
    "name": "set_checklist_item",
    "purpose": "rename or tick a checklist item.",
    "inputs": "item_id, label, is_done (give at least one).",
    "returns": "{item} (the Task as get_task returns it).",
    "errors": "invalid_input, not_found (item_id), forbidden, rate_limited.",
    "args": [
      {
        "name": "item_id",
        "type": "uuid",
        "required": true
      },
      {
        "name": "label",
        "type": "text",
        "required": false
      },
      {
        "name": "is_done",
        "type": "boolean",
        "required": false
      }
    ]
  },
  {
    "name": "set_key_result_current_value",
    "purpose": "record where a key result stands; allowed for an ops lead, an admin, and the head of the Objective's own Business Unit.",
    "inputs": "key_result_id; current_value (a finite number smaller than 1000000000000000 in size with at most 6 decimal places, or null to clear); expected_updated_at (optional; a newer one is a conflict).",
    "returns": "{item} (the key result plus objective_id).",
    "errors": "invalid_input (current_value), not_found, forbidden, conflict, rate_limited. This operation has no input for targets, units, due dates, owners or adding or removing key results and never returns refused.targets; only refused_action answers such a request with refused.targets.",
    "args": [
      {
        "name": "key_result_id",
        "type": "uuid",
        "required": true
      },
      {
        "name": "current_value",
        "type": "numeric",
        "required": true
      },
      {
        "name": "expected_updated_at",
        "type": "timestamp with time zone",
        "required": false
      }
    ]
  },
  {
    "name": "whoami",
    "purpose": "who is calling and what they may do.",
    "inputs": "none.",
    "returns": "{person {id, full_name, email}, org_id, access_roles, teams [{team_id, name, business_unit_id, is_primary}], authority {signal, work}} where authority is what the Signal-post and Work write-scope authority functions return for the caller.",
    "errors": "none expected.",
    "args": []
  }
]
